# DATA PREPARATION

In [1]:
# INITIATION: PYTHON AND DISPLAY

# Import libraries
import pandas as pd #
import numpy as np
import ipywidgets as widgets
import matplotlib.pyplot as plt #charts
import seaborn as sns #charts
from pivot_utils import create_pivot_ui #This is my own customised Pivot Table Function

# For better visibility
from IPython.display import display, HTML

# Apply a no-wrap style to prevent text wrapping
display(HTML("""
<style>
.dataframe td { white-space: nowrap; }
</style>
"""))

# Set the option to display all columns
pd.set_option('display.max_columns', None)

# Set the option to display all rows
pd.set_option('display.max_rows', None)

# Set the float format to use a space as a thousands separator and a comma as a decimal separator
pd.set_option('display.float_format', lambda x: f'{x:,.2f}'.replace(',', ' ').replace('.', ','))

In [2]:
# FILE LOAD

# Read the Excel file into a DataFrame
df_filter = pd.read_excel('2000 Analysis Python CHANGED.xlsx', decimal=',')

# DESCRIPTIVE ANALYSIS

In [3]:
create_pivot_ui(df_filter, 
                default_index=['Growth_Category'], 
                default_columns='P/F',            
                default_values='Sales',             
                default_filter_column='Year',       
                default_filter_value=2022)

Dropdown(description='Filter by Year:', index=1, options=(None, 2022, 2021, 2020, 2019), value=2022)

SelectMultiple(description='Index', index=(52,), options=('#', 'Name', 'NIP', 'GPW', 'Funded KRS', 'Funded Bus…

Dropdown(description='Columns', index=39, options=('#', 'Name', 'NIP', 'GPW', 'Funded KRS', 'Funded Business',…

Dropdown(description='Values', index=6, options=('#', 'Funded KRS', 'Funded Business', 'PKD', 'Owner Type', 'Y…

Dropdown(description='Aggregation', index=2, options=('sum', 'mean', 'count', 'Percentage of Total', 'Percenta…

Dropdown(description='Sort by Column', options=('Total', 'G0', 'G1', 'G2', 'G3', 'Total'), value='Total')

Dropdown(description='Column Sort', index=2, options=('Ascending', 'Descending', 'None'), value='None')

Dropdown(description='Sort by Row', options=('Total', 'F', 'P', 'Total'), value='Total')

Dropdown(description='Row Sort', index=2, options=('Ascending', 'Descending', 'None'), value='None')

Button(button_style='success', description='Export to Excel', style=ButtonStyle(), tooltip='Click to export th…

Output()

Output()

In [5]:
# Grouping by the Growth_Category
grouped_data = df_filter[df_filter['Year'] == 2022].groupby('Growth_Category', observed=False).size()
display(grouped_data)

Growth_Category
G0    425
G1    587
G2    316
G3    181
dtype: int64

In [6]:
pivot_growth = df_filter.loc[(df_filter['Year'] == 2022) & (df_filter['Hint'] == 'No')].pivot_table(
    index=['Growth_Category', 'Hint'], 
    columns='P/F', 
    values='Sales', 
    aggfunc='count', 
    observed=False, 
    margins=True  # Adds totals
)

display (pivot_growth)


pivot_strength = df_filter[df_filter['Year'] == 2022].pivot_table(
    index=['Growth_Category','Hint'], 
    columns='P/F', 
    values='Starting_BS_Strength', 
    observed=False, 
    margins=True #margins adds totals
)
display (pivot_strength)

P/F                     F    P  All
Growth_Category Hint
G0              No    118  131  249
G1              No    147  173  320
G2              No     57  120  177
G3              No     22   76   98
All                   344  500  844

P/F                     F    P  All
Growth_Category Hint
G0              No   0,32 0,38 0,35
                Yes  0,47 0,41 0,45
G1              No   0,43 0,38 0,40
                Yes  0,50 0,52 0,51
G2              No   0,40 0,42 0,41
                Yes  0,44 0,49 0,46
G3              No   0,26 0,41 0,38
                Yes  0,48 0,41 0,45
All                  0,43 0,42 0,43

In [7]:
# Calculate mean

mean = df_filter[df_filter['Year'] == 2022]['Starting_BS_Strength'].mean(skipna=True)

mean2019 = df_filter[df_filter['Year'] == 2019]['Starting_BS_Strength'].mean(skipna=True)

mean2 = df_filter[df_filter['Year'] == 2022]['BS_Strength'].mean(skipna=True)

mean20192 = df_filter[df_filter['Year'] == 2019]['BS_Strength'].mean(skipna=True)

print (mean, mean2019)

print (mean2, mean20192)

0.4264259439891672 0.4264259439891672
0.43244556862631456 0.4264259439891672

In [8]:
# Filter the dataframe for the year 2022 and Owner Type 400
filtered_data = df_filter[(df_filter['Year'] == 2022) & (df_filter['Owner Type'] == 400)]

# Group by Growth_Category and count the occurrences in each group
grouped_data = filtered_data.groupby('Growth_Category', observed=False).size()

# Display the result
print(grouped_data)

Growth_Category
G0    128
G1    206
G2    153
G3     94
dtype: int64