# DATA PREPARATION

In [12]:
# INITIATION: PYTHON AND DISPLAY

# Import libraries
import pandas as pd #
import numpy as np

# For better visibility
from IPython.display import display, HTML

# Apply a no-wrap style to prevent text wrapping
display(HTML("""
<style>
.dataframe td { white-space: nowrap; }
</style>
"""))

# Set the option to display all columns
pd.set_option('display.max_columns', None)

# Set the option to display all rows
pd.set_option('display.max_rows', None)

# Set the float format to use a space as a thousands separator and a comma as a decimal separator
pd.set_option('display.float_format', lambda x: f'{x:,.2f}'.replace(',', ' ').replace('.', ','))

In [13]:
# FILE LOAD

# Read the Excel file and specify that 'PKD' should be read as a string to preserve leading zeros
df = pd.read_excel('2000 Analysis Python.xlsx', decimal=',', dtype={'PKD': str})

pkd = pd.read_excel('2000 PKD.xlsx')  # Load the pkd data

companies = pd.read_excel('2000 Companies.xlsx')

# Convert 'PKD' to string and extract the first two characters (keeping leading zeros)
df['PKD_2'] = df['PKD'].astype(str).str.zfill(2).str[:2]

# Convert the 'PKD_2' column in pkd to a string to match the type of 'PKD'
pkd['PKD_2'] = pkd['PKD_2'].astype(str).str.zfill(2)

# Perform the merge using 'PKD' and 'Number'
df = pd.merge(
    df,
    pkd,
    left_on='PKD_2',
    right_on='PKD_2',
    how='left'
)

cols = df.columns.tolist()  # Get a list of all column names
cols.insert(30, cols.pop(cols.index('PKD_2'))) # Remove 'PKD_2' and insert it at index 30
df = df[cols]  # Reassign the DataFrame with the new column order

# Select the columns and make a copy to avoid the SettingWithCopyWarning
columns_to_select = [5, 0, 1, 2, 3]

companies_subset = companies.iloc[:, columns_to_select].copy()

# Rename the columns with meaningful names
companies_subset.columns = ['NIP', 'L2022', 'L2021', 'L2020', 'L2019']

# Perform the merge
df = pd.merge(
    df,
    companies_subset,
    on='NIP',
    how='left'
)

In [14]:
# FILE INSPECTION

# Print the number of rows and columns
print(f"Number of rows and columns: {df.shape}")

# Display the first 5 rows of the DataFrame
display(df.head())

# Print the last 5 rows of the DataFrame
display(df.tail())

Number of rows and columns: (8136, 39)

,#,Name,NIP,GPW,Funded KRS,Funded Business,Foreign Branches,PKD,Owner Type,Year,Sales,Gross Profit,Operating Profit,Net Profit,Depreciation,Export Sales,Employment,Staff costs,Salaries,Salary related,BS,Fixed Assets,Current Assets,Equity,Liabilities,Export as % of sales,ROA,ROS,ROE,PKD_1,PKD_2,PKD_1 Description,PKD_2 Description,Quartile of digital intensity: 2001-03,Quartile of digital intensity: 2013-15,L2022,L2021,L2020,L2019
0,"1,00","Orlen SA GK, Płock",7740001454,SG),"1 999,00","1 944,00",Tak,1920,412,2022,"277 564 000,00","41 093 000,00","40 593 000,00","33 630 000,00","6 916 000,00","114 120 000,00","64 494,00","6 406 000,00","5 385 000,00","1 021 000,00","272 327 000,00","153 117 000,00","119 210 000,00","136 959 000,00","135 368 000,00","0,41","0,12","0,15","0,25",C,19,Manufacturing,MANUFACTURE AND PROCESSING OF COKE AND REFINED...,Medium-high,Medium-high,1,"1,00","1,00","1,00"
1,"2,00","Jeronimo Martins Polska SA, Kostrzyn",7791011327,NaN,"1 995,00",NaN,NaN,4719,500,2022,"85 034 775,00","4 109 337,00","4 254 158,00","3 414 175,00","1 207 337,60","0,00","77 726,70","5 186 427,00","4 171 040,00","1 015 387,00","23 866 577,00","10 897 620,00","12 968 957,00","4 653 067,00","18 097 341,00","0,00","0,14","0,05","0,73",G,47,Wholesale and Retail Trade; Repair of Motor Ve...,"RETAIL TRADE, EXCEPT OF MOTOR VEHICLES",Medium-high,Medium-high,2,"3,00","2,00","2,00"
2,"3,00","PGE Polska Grupa Energetyczna GK SA, Lublin",5260250541,SG),"2 007,00","1 990,00",NaN,7010,145,2022,"73 435 000,00","4 299 000,00","4 110 000,00","3 390 000,00","1 103 000,00","29 000,00","38 013,00","5 033 000,00","4 224 000,00","809 000,00","105 778 000,00","71 732 000,00","34 046 000,00","54 383 000,00","51 395 000,00","0,00","0,03","0,06","0,06",M,70,"Professional, Scientific and Technical Activities",ACTIVITIES OF HEAD OFFICES; MANAGEMENT CONSULT...,High,High,3,"4,00","3,00","4,00"
3,"4,00","LG Energy Solution Wrocław sp. z o.o., Wrocław",8961550941,NaN,"2 016,00",NaN,NaN,2720,500,2022,"40 736 584,00","2 273 691,00","1 892 236,00","1 772 021,00","2 053 927,00","33 690 570,00","7 154,00","967 979,00","760 145,00","207 834,00","34 420 555,00","17 242 707,00","17 177 848,00","6 746 432,00","23 448 517,00","0,83","0,05","0,06","0,26",C,27,Manufacturing,MANUFACTURE OF ELECTRICAL EQUIPMENT,Medium-high,Medium-high,4,"8,00","14,00","45,00"
4,"5,00","Totalizator Sportowy sp. z o.o. GK, Warszawa",5250010982,NaN,"1 956,00",NaN,NaN,9200,100,2022,"39 425 832,00","423 173,00","451 477,00","363 507,00","135 259,00","0,00","5 354,00","609 740,50","486 298,50","123 442,00","2 614 625,50","953 078,00","1 661 547,50","1 545 806,00","982 775,00","0,00","0,14","0,01","0,24",R,92,"Arts, Entertainment and Recreation",GAMBLING AND BETTING ACTIVITIES,Medium-low,Medium-high,5,"11,00","17,00","30,00"

,#,Name,NIP,GPW,Funded KRS,Funded Business,Foreign Branches,PKD,Owner Type,Year,Sales,Gross Profit,Operating Profit,Net Profit,Depreciation,Export Sales,Employment,Staff costs,Salaries,Salary related,BS,Fixed Assets,Current Assets,Equity,Liabilities,Export as % of sales,ROA,ROS,ROE,PKD_1,PKD_2,PKD_1 Description,PKD_2 Description,Quartile of digital intensity: 2001-03,Quartile of digital intensity: 2013-15,L2022,L2021,L2020,L2019
8131,NaN,"Albea Poland sp. z o.o., Łódź",5252332773,NaN,NaN,NaN,NaN,2229,500,2019,"320 844,00","28 137,00","29 254,00","22 720,00","16 641,00","247 698,00","647,00","56 245,00","44 790,00","11 455,00","243 973,00","150 708,00","93 266,00","170 654,00","67 836,00","0,77","0,09","0,09","0,13",C,22,Manufacturing,MANUFACTURE OF RUBBER AND PLASTIC PRODUCTS,Medium-low,Medium-low,NaN,NaN,"1 717,00","1 807,00"
8132,NaN,"Flokk sp. z o.o., Turek",6680000366,NaN,"2 017,00",NaN,NaN,3101,500,2019,"441 486,85","28 565,00","27 122,00","30 298,00","21 165,00","327 390,00","1 376,00","105 927,00","87 162,00","18 765,00","534 159,00","320 722,00","213 437,00","461 552,00","43 028,00","0,74","0,06","0,06","0,07",C,31,Manufacturing,MANUFACTURE OF FURNITURE,Medium-high,Medium-high,NaN,"1 897,00","1 855,00","1 286,00"
8133,NaN,"Stalexport Autostrady SA GK, Katowice",6340134211,NaN,"1 963,00",NaN,NaN,4211,540,2019,"351 487,00","129 153,00","124 772,00","80 396,00","57 005,00","0,00","335,00",NaN,NaN,NaN,"1 322 052,00","918 245,00","403 807,00","795 764,00","526 288,00","0,00","0,06","0,37","0,10",F,42,Construction,CIVIL ENGINEERING WORKS,Low,Low,NaN,NaN,"1 887,00","1 645,00"
8134,NaN,Konica Minolta Business Solutions Polska sp. z...,5260204908,NaN,"1 991,00","1 878,00",2023,4666,500,2019,"375 672,00","8 973,00","146,00","449,00","47 474,00","5 807,00","396,00","68 204,70","56 243,70","11 961,00","417 658,00","227 601,00","190 056,00","79 721,00","325 250,00","0,02","0,00","0,02","0,01",G,46,Wholesale and Retail Trade; Repair of Motor Ve...,"WHOLESALE TRADE, EXCEPT OF MOTOR VEHICLES",Medium-high,Medium-high,NaN,NaN,"1 829,00","1 544,00"
8135,NaN,"Fuji Seal Poland sp. z o.o., Kutno",5252335702,NaN,NaN,NaN,NaN,2222,500,2019,"291 940,00","10 828,00","9 548,00","9 298,00","21 803,00","266 026,00","454,00","43 340,13","34 655,13","8 685,00","291 405,00","225 927,00","65 478,00","159 252,00","119 461,00","0,91","0,03","0,04","0,06",C,22,Manufacturing,MANUFACTURE OF RUBBER AND PLASTIC PRODUCTS,Medium-low,Medium-low,NaN,"1 773,00","1 721,00","1 958,00"

In [15]:
# DATA CLEAN-UP

# Step 1: Identify duplicates based on 'Name' and 'Year' columns
duplicates = df[df.duplicated(subset=['Name', 'Year'], keep=False)]

# Step 2: Display the duplicates for inspection
print("Duplicate rows based on 'Name' and 'Year':")
print(duplicates)

Duplicate rows based on 'Name' and 'Year':
Empty DataFrame
Columns: [#, Name, NIP, GPW, Funded KRS, Funded Business, Foreign Branches, PKD, Owner Type, Year, Sales, Gross Profit, Operating Profit, Net Profit, Depreciation, Export Sales, Employment, Staff costs, Salaries, Salary related, BS, Fixed Assets, Current Assets, Equity, Liabilities, Export as % of sales, ROA, ROS, ROE, PKD_1, PKD_2, PKD_1 Description, PKD_2 Description, Quartile of digital intensity: 2001-03, Quartile of digital intensity: 2013-15, L2022, L2021, L2020, L2019]
Index: []

In [16]:
#DATA TYPES ASSIGNMENT

# Step 1: Changing data types for analysis
dtype_changes = {
    
    'PKD': 'category',
    'PKD_2': 'category',
    'PKD_1': 'category',
    'Owner Type': 'category',
    'Year': 'category',
    'Sales': 'float',
    'Gross Profit': 'float',
    'Operating Profit': 'float',
    'Net Profit': 'float',
    'Depreciation': 'float',
    'Export Sales': 'float',
    'Employment': 'float',
    'Staff costs': 'float',
    'Salaries': 'float',
    'Salary related': 'float',
    'BS': 'float',
    'Operating Profit': 'float',
    'Fixed Assets': 'float',
    'Current Assets': 'float',
    'Equity': 'float',
    'Liabilities': 'float',
    'Export as % of sales': 'float',
    'ROA': 'float',
    'ROS': 'float',
    'ROE': 'float',
    'L2022': 'float'
    
    
    }
# Step 2: Check each column individually to identify possible issues

for col, dtype in dtype_changes.items():
    try:
        if dtype in ['float', 'int']:  # Check if the target type is numeric
            df[col] = pd.to_numeric(df[col], errors='coerce')  # Use pd.to_numeric for numeric conversion
        df[col] = df[col].astype(dtype)  # Convert to the target dtype
        print(f"Successfully converted {col} to {dtype}")
    except ValueError as e:
        print(f"Error converting {col} to {dtype}: {e}")

Successfully converted PKD to category
Successfully converted PKD_2 to category
Successfully converted PKD_1 to category
Successfully converted Owner Type to category
Successfully converted Year to category
Successfully converted Sales to float
Successfully converted Gross Profit to float
Successfully converted Operating Profit to float
Successfully converted Net Profit to float
Successfully converted Depreciation to float
Successfully converted Export Sales to float
Successfully converted Employment to float
Successfully converted Staff costs to float
Successfully converted Salaries to float
Successfully converted Salary related to float
Successfully converted BS to float
Successfully converted Fixed Assets to float
Successfully converted Current Assets to float
Successfully converted Equity to float
Successfully converted Liabilities to float
Successfully converted Export as % of sales to float
Successfully converted ROA to float
Successfully converted ROS to float
Successfully converted ROE to float
Successfully converted L2022 to float

In [17]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8136 entries, 0 to 8135
Data columns (total 39 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   #                                       7998 non-null   float64
 1   Name                                    8136 non-null   object
 2   NIP                                     8136 non-null   object
 3   GPW                                     548 non-null    object
 4   Funded KRS                              1564 non-null   float64
 5   Funded Business                         220 non-null    float64
 6   Foreign Branches                        248 non-null    object
 7   PKD                                     8136 non-null   category
 8   Owner Type                              8136 non-null   category
 9   Year                                    8136 non-null   category
 10  Sales                                   8109 non-null   float64
 11  Gross Profit                            8051 non-null   float64
 12  Operating Profit                        8057 non-null   float64
 13  Net Profit                              8071 non-null   float64
 14  Depreciation                            8040 non-null   float64
 15  Export Sales                            7963 non-null   float64
 16  Employment                              7977 non-null   float64
 17  Staff costs                             8007 non-null   float64
 18  Salaries                                8006 non-null   float64
 19  Salary related                          7994 non-null   float64
 20  BS                                      8058 non-null   float64
 21  Fixed Assets                            8054 non-null   float64
 22  Current Assets                          8051 non-null   float64
 23  Equity                                  8061 non-null   float64
 24  Liabilities                             8057 non-null   float64
 25  Export as % of sales                    8136 non-null   float64
 26  ROA                                     8136 non-null   float64
 27  ROS                                     8136 non-null   float64
 28  ROE                                     8135 non-null   float64
 29  PKD_1                                   8136 non-null   category
 30  PKD_2                                   8136 non-null   category
 31  PKD_1 Description                       8136 non-null   object
 32  PKD_2 Description                       8136 non-null   object
 33  Quartile of digital intensity: 2001-03  8136 non-null   object
 34  Quartile of digital intensity: 2013-15  8136 non-null   object
 35  L2022                                   7985 non-null   float64
 36  L2021                                   6673 non-null   float64
 37  L2020                                   6437 non-null   float64
 38  L2019                                   6205 non-null   float64
dtypes: category(5), float64(26), object(8)
memory usage: 2.2+ MB

None

In [18]:
# Save integrated file
df.to_excel('2000 Analysis Python INTEGRATED.xlsx', index=False)

print("DataFrame 'df' has been saved to '2000 Analysis Python INTEGRATED.xlsx'.")

DataFrame 'df' has been saved to '2000 Analysis Python INTEGRATED.xlsx'.

In [19]:
Lista_2019_2022 = df[['Name', 'NIP', 'L2019', 'L2022']][(df['Year'] == 2022) & df['L2019'].notna() & df['L2022'].notna()]


Lista_2019_2022.to_excel('Lista_2019_2022.xlsx', index=False)

print("DataFrame 'Lista_2019_2022' has been saved to 'Lista_2019_2022.xlsx'.")

DataFrame 'Lista_2019_2022' has been saved to 'Lista_2019_2022.xlsx'.

# ANALYSIS  SET-UP

In [21]:
#SET THE MAIN FILTERS FOR THE ANALYSIS

# Identify the names with Sales = 0 or Employment = 0 in 2019 or 2022
names_to_remove = df[
    (df['Year'].isin([2019, 2022])) & 
    (
        (df['Sales'] == 0) | pd.isnull(df['Sales']) |
        (df['Employment'] == 0) | pd.isnull(df['Employment'])
    )
]['Name'].unique() 

# Apply the filters
df_filter = df[
    df['L2019'].notna() &
    (~df['Name'].isin(names_to_remove))
]

# Show results
print(f"Number of companies with sales or employment in 2019 or 2022 equal to 0 is: {len(names_to_remove)}")
print(f"Number of companies, which did not appear on the 2000 List in 2022 is: {len(df[df['L2022'].isna()])}")

print(f"Number of companies after clean-up: {len(df_filter[df_filter['Year'] == 2022]['Sales'])}")

Number of companies with sales or employment in 2019 or 2022 equal to 0 is: 115
Number of companies, which did not appear on the 2000 List in 2022 is: 151
Number of companies after clean-up: 1515

In [22]:
#Lista firm usuniętych z analizy
df_print = df[df['Name'].isin(names_to_remove)]

display(df_print.pivot(index='Name', columns='Year', values='Sales'))
df_print.to_excel('filtered_data.xlsx', index=False)  # Save the filtered DataFrame to an Excel file

Year,2019,2020,2021,2022
Name,,,,
"7R Development Management sp. z o.o., Kraków","104 909,00","406 831,44","406 831,44","456 893,50"
"Accenture sp. z o.o. GK, Warszawa",NaN,NaN,"1 586 932,00","2 095 218,00"
"Agro Kontrakt sp. z o.o., Olsztyn","0,00","0,00","675,00","611 978,40"
"Aquila Radomsko sp. z o.o., Radomsko","251 800,00","242 966,00","342 096,93","407 942,00"
"Aramco Fuels Poland sp. z o.o., Gdańsk","0,00","0,00","0,00","5 033 149,00"
"Archigrest sp. z o.o., Warszawa",NaN,NaN,"439 219,00","578 535,00"
"B8 sp. z o.o. Baltic sp.k.a., Gdańsk","274 092,94","327 867,00","266 965,95","458 564,44"
"Baywa R.E. Solar Systems sp. z o.o., Zabierzów","0,00","0,00","298 812,06","743 669,00"
"Benzol sp. z o.o., Ostrołęka","235 198,98","190 145,48","281 486,18","421 783,12"
"Biofarm sp. z o.o., Poznań","324 930,97","329 758,89","418 306,48","417 543,80"
"CMC OIL sp.z o.o., Gnojnik","0,00","0,00","47 554,65","544 512,62"
"Control Process SA, Kraków","1 363 391,00","937 198,00","1 257 497,00","1 542 328,00"
"Coral Travel sp. z o.o., Warszawa",NaN,NaN,"1 037 369,00","1 862 634,00"
"DNP sp. z o.o., Wyrzysk","258 873,31","375 877,66","528 804,64","761 451,99"
"Dachser sp. z o.o., Stryków","494 407,00","547 234,50","715 540,93","904 969,80"
"Dan-Pol sp.c., Żagań","0,00","234 518,96","295 829,75","455 805,16"
"EME AERO sp. z o.o., Jasionka","0,00","448 449,00","1 499 015,00","3 512 575,00"
"EMIX-OIL sp. z o.o., Lututów","0,00","0,00","326 757,90","434 567,80"
"EP Resources PL SA, Katowice","344 279,00","349 178,00","307 334,00","476 225,00"
"ESPPOL Trade SA, Warszawa","0,00","979 925,61","3 263 752,93","4 407 871,93"
"EXG Capital sp. z o.o. sp.j., Częstochowa","386 721,43","224 952,24","229 071,05","472 643,51"
"Elektrociepłownia Stalowa Wola SA, Stalowa Wola",NaN,"1 021 625,09","1 021 625,09","2 507 204,69"
"Enteneo Energy Trading sp. z o.o.,","116 244,20","129 247,08","277 537,65","735 947,06"
"Eupoltrans sp. z o.o., Sady","0,00","1 948,90","93 096,75","414 138,79"
"Ewl Outsourcing sp. z o.o., Piaseczno","74 785,41","175 257,06","321 214,85","519 945,64"
"Exclusive Networks Poland SA, Kraków","0,00","0,00","1 018 843,00","1 050 863,41"
"Firma Kojs, Jabłonka",NaN,"303 449,61","303 449,61","524 858,80"
"Firma Oaza, Rybarzowice","243 670,40","227 609,01","312 269,94","471 611,51"
"Foodcom SA, Warszawa","148 458,22","214 883,06","397 400,85","658 362,24"
"Fortum Silesia SA, Zabrze","257 923,37","246 414,60","318 584,12","431 436,39"
"Girpoltrans sp. z o.o., Komorniki","0,00","239 893,34","472 044,44","735 674,73"
"Goldbeck Solar Polska sp. z o.o., Komorniki","0,00","0,00","200 129,90","480 167,95"
"Grodno SA, Nieporęt","579 700,00","679 387,00","1 177 023,00","1 223 628,00"
"Grupa Cichy Zasada sp. z o.o. sp.j., Wysogotowo","0,00","0,00","2 554 774,43","2 624 574,70"
"Grupa FAKRO, Nowy Sącz","620 546,90","618 550,63","1 500 000,00","1 500 000,00"
"Grupa Polmlek, Warszawa",NaN,"4 200 000,00","5 700 000,00","9 821 937,00"
"Grupa Producentów Drobiu sp. z o.o., Bolesławiec","287 013,00","344 871,75","443 031,98","668 512,00"
"Grupa Strabag w Polsce, Pruszków",NaN,NaN,"5 082 750,00","5 068 281,00"
Grupy Fortum w Polsce,NaN,NaN,"5 418 589,00","9 010 300,00"
"HUAWEI Polska sp. z o.o., Warszawa","3 639 562,00","2 935 159,00","2 379 650,00","2 854 772,00"
"Halfprice sp. z o.o., Polkowice","0,00","0,00","137 221,89","683 720,39"
"Hanseatic Produkcja sp. z o.o., Grudziądz","0,00","1 643,02","202 535,55","487 051,00"
"Harden Construction Poland sp. z o.o., Warszawa","0,00","0,00","30 434,92","470 058,71"
"Huta Pokój Profile sp. z o.o., Ruda Śląska","0,00","257 373,75","553 670,47","466 518,43"
"Hyperoil sp. z o.o., Piaseczno","0,00","316 169,61","316 169,61","1 311 915,00"
"INPOST sp. z o.o., Kraków","398 558,00","2 373 267,00","3 395 458,00","4 131 296,00"
"Inpost Paczkomaty sp. z o.o., Kraków","850 665,00","1 024 870,00","1 211 017,00","1 225 664,00"
"Joker sp.j., Szczecin","1 176 827,00","1 235 964,00","1 235 964,00","1 575 609,71"
"KION Polska sp. z o.o., Kołbaskowo","0,00","0,00","179 745,21","444 484,52"
"Kantor Wymiany Walut sp.j., Gorzów Wlkp.","569 920,39","616 668,48","622 433,48","669 349,00"
"Koliber Energy Trading sp. z o.o., Warszawa",NaN,NaN,"0,00","507 946,06"
"Koral Trade sp. z o.o., Nowy Sącz",NaN,"0,00","0,00","404 498,69"
"La Lorraine Polska sp. z o.o., Nowy Dwór Mazowiecki","553 052,00","507 475,00","570 715,00","812 785,00"
"Leroy Merlin Inwestycje sp. z o.o., Warszawa","310 139,00","341 673,13","404 165,00","456 245,44"
"MSD Polska Dystrybucja sp. z o.o., Warszawa","518 309,00","508 056,12","571 177,75","650 318,00"
"Makrochem SA sp.j., Lublin","0,00","0,00","526 505,57","1 192 247,68"
"Marketing Investment Group SA, Kraków","1 044 650,00","834 548,00","1 010 133,34","1 413 298,00"
"Media Saturn Logistyka sp. z o.o., Warszawa","456 004,00","731 719,00","1 817 816,90","2 339 648,96"
"Menlo Electric SA, Warszawa","0,00","830,45","226 981,00","715 290,89"
"Miele Technika sp. z o.o., Ksawerów","359 262,00","478 599,14","478 599,14","514 707,71"
"Milkpol Polska sp. z o.o., Warszawa","18 728,28","18 755,58",NaN,"1 259 742,57"
"Miropasz sp.z o.o.., Grójec","209 082,62","239 648,10","31 589,89","529 732,79"
"Müller Dairy Polska sp. z o.o., Poznań","312 564,00","377 889,00","457 110,80","704 894,06"
"NKT SA, Czechowice-Dziedzice","1 011 053,00","1 082 160,00","1 747 762,00","1 993 976,00"
"Okręgowa Spółdzielnia Mleczarska, Krasnystaw","370 910,00","363 148,09","382 532,09","433 089,08"
"Opella Healthcare Poland sp. z o.o., Warszawa","0,00","0,00","0,00","605 664,17"
"Osadkowski sp. z o.o., Bierutów","1 194 439,00","1 359 656,00","1 681 837,00","2 071 582,00"
"P4 Sp. z o.o. GK, Warszawa","7 040 753,00","7 159 846,00","7 302 306,00","8 934 847,00"
"PHUP Merkury sp.j., Kraków","879 180,00","991 246,96","903 981,53","1 213 810,00"
"PLWD sp. z o.o., Świecie",NaN,"292 381,97","292 381,97","2 017 330,42"
"PRESS GLASS sp. z o.o., Konopiska","0,00","0,00","1 296 077,88","1 902 972,97"
"Paged Morąg SA, Morąg","256 840,00","209 743,00","337 167,00","496 003,00"
"Panattoni Construction Europe sp. z o.o., Warszawa","479 992,00","63 203,00","355 201,00","1 253 723,34"
"Pfleiderer MDF sp. z o.o., Grajewo","232 686,00","247 706,00","336 418,00","447 826,00"
"Pfleiderer Polska sp. z o.o., Wrocław","1 371 187,00","1 288 435,00","1 665 458,00","2 545 266,00"
"Pfleiderer Wieruszów sp. z o.o., Wieruszów","485 600,00","449 225,00","569 696,00","720 007,00"
"Pol Power sp. z o.o., Komorniki","344 240,00","391 587,00","456 143,51","499 382,24"
"Polenergia Fotowoltaika SA, Warszawa",NaN,"366 338,19","366 338,19","400 604,37"
"Polski Holding Nieruchomości SA GK, Warszawa","209 100,00","733 700,00","480 500,00","627 000,00"
"Polski Tytoń SA, Radom","0,00","381 282,37","381 282,37","1 844 849,60"
"Pozkrone sp.c., Poznań",NaN,NaN,"403 892,34","515 218,03"
"Press Glass Holding SA, Konopiska",NaN,"1 737 585,00","2 283 647,00","3 131 046,00"
"Promedica24 EU sp. z o.o. sp.j., Warszawa","0,00","191 981,00","410 548,55","411 088,93"
"RB (Hygiene Home) Poland sp. z o.o., Nowy Dwór Mazowiecki","0,00","639 766,00","775 398,00","855 795,00"
"Rainbow Tours SA GK, Łódź","1 745 960,00","434 456,00","1 279 424,00","2 393 306,00"
"Rekord Hale Namiotowe sp. z o.o., Wrocław","207 348,59","184 804,46","265 707,70","936 241,80"
"Rhenus Freight Logistics sp. z o.o., Warszawa","0,00","0,00","0,00","441 819,00"
"SDM Manufaktura sp. z o.o., Konstancin-Jeziorna","0,00","106 530,00","491 253,00","841 776,00"
"STS Holding SA, Katowice","0,00","0,00","497 631,00","579 051,00"
"Sarzyna Chemical sp. z o.o., Nowa Sarzyna","0,00","284 418,29","537 685,05","602 198,99"
"Sikora -AC sp. z o.o., Mikołów","279 936,94","352 438,00","494 657,72","543 912,71"
"Sk Hi Tech Battery Materials Poland sp. z o.o., Dąbrowa Górnicza","0,00","0,00","147 850,23","408 934,70"
"Solaris Bus & Coach SA, Owińska","2 606 316,00","3 107 901,00","3 308 580,00","3 269 369,00"
"Spar sp. z o.o., Poznań","0,00","5 061,40","866 661,00","597 828,51"
"Spectris Energy sp. z o.o., Wraszawa","0,00","3 779,52","185 404,04","473 256,18"
"Stalprofil SA GK, Dąbrowa Górnicza","1 429 256,00","1 550 757,00","1 648 282,00","2 215 582,00"
"Stellantis Gliwice sp. z o.o., Gliwice",NaN,"19 213,79","2 224 664,00","2 679 349,00"
"Super Grupa Pl sp. z o.o., Gdańsk","154 779,80","487 958,00","647 621,95","886 572,36"
"Superhobby Dom i Ogród sp. z o.o., Warszawa","2 033 044,00","2 895 675,00","3 372 908,00","4 140 898,80"
"T-Mobile Polska SA, Warszawa","6 186 821,00","6 197 955,00","6 259 275,00","6 436 354,00"
"TADMAR sp. z o.o., Poznań","0,00","0,00","460 886,00","540 660,16"
"TATENEN sp. z o.o., Jarosław","0,00","18 253,31","45 655,98","616 715,09"
"Transeu Poland sp. z o.o., Sady","0,00","0,00","102 505,98","408 915,87"
"Transport Towarowy Handel Opałem, Gomunice",NaN,"43 574,54","54 951,39","496 503,10"
"Trend Energy Solutions SA, Warszawa","0,00","260 721,81","260 721,81","1 362 581,09"
"Ulenberg , Rzuszcze","177 847,02","220 607,94","257 560,16","398 879,91"
"Venor Polska sp. z o.o., Kraków",NaN,NaN,"249 244,49","508 244,98"
"Versuni Poland sp. z o.o., Warszawa","0,00","0,00","329 799,00","597 943,00"
"Warsaw Gas Trading sp. z o.o., Warszawa","676 140,88","747 888,43","1 288 856,60","2 227 095,81"
"Warsaw Trading Partners sp. z o.o., Warszawa","5 112 765,00","7 651 521,00","6 646 067,00","6 713 511,34"
"Werner Kenkel sp. z o.o., Krzycko Wielkie","688 529,97","679 310,94","823 882,03","1 013 283,00"
"Wielkopolski Indyk sp. z o.o., Mosina","274 567,67","302 341,94","368 932,85","500 575,93"
"Wirtualna Polska Media SA, Warszawa","371 425,00","403 082,00","491 740,00","571 233,00"
"ZPM JBB Import-Export Józef Bałdyga, Łyse","976 876,64","1 064 548,11","1 058 298,88","1 337 324,21"
"Śnieżka Trade Of Colours sp. z o.o., Warszawa","17 521,53","567 444,00","567 444,00","569 925,00"

In [23]:
#CHECK OF FILTERING

# Select the columns you want to include in the groupby and describe operations
selected_columns = ['Sales', 'Employment']

# Group by 'P/F' and 'Year' and apply describe to the selected columns only
df_summary = df.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
df_filter_summary = df_filter.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
display(df_summary, df_filter_summary)

# Show max and min company
selected_columns = ['Name','Sales', 'Employment']
display(df_filter['Name'].nunique())
display(df_filter.loc[df_filter['Sales'].idxmax(),selected_columns])
display(df_filter.loc[df_filter[df_filter['Year'] == 2022]['Sales'].idxmin(),selected_columns])

display(df_filter[selected_columns].head())

Year                       2019          2020           2021           2022
Sales      count       2 017,00      2 026,00       2 032,00       2 034,00
           mean    1 185 203,11  1 201 930,70   1 479 562,02   1 953 531,56
           std     3 523 189,91  3 302 545,96   4 302 033,93   7 387 258,01
           min             0,00          0,00           0,00     368 609,79
           25%       316 485,28    327 677,48     412 518,24     525 459,10
           50%       501 741,00    508 354,11     628 892,35     796 314,88
           75%       957 376,00    961 828,50   1 151 565,25   1 426 674,68
           max   111 203 000,00 86 180 000,00 131 341 000,00 277 564 000,00
Employment count       1 985,00      1 991,00       2 003,00       1 998,00
           mean        1 301,41      1 337,15       1 476,20       1 397,51
           std         3 827,95      3 992,54       6 088,64       4 174,72
           min             0,00          0,00           0,00           0,00
           25%           151,00        159,00         177,50         188,25
           50%           440,00        452,00         476,00         480,00
           75%         1 037,00      1 063,50       1 109,50       1 127,00
           max        80 116,00     78 873,00     206 512,00      77 726,70

Year                       2019          2020           2021           2022
Sales      count       1 514,00      1 514,00       1 514,00       1 515,00
           mean    1 431 360,88  1 426 524,06   1 733 238,20   2 272 020,44
           std     3 978 930,30  3 704 758,88   4 849 381,60   8 451 308,42
           min         4 743,00     14 316,00      53 764,00     368 609,79
           25%       417 352,25    414 922,50     497 438,84     607 107,65
           50%       622 581,50    624 048,07     753 978,23     922 914,73
           75%     1 128 125,79  1 118 723,75   1 325 827,00   1 654 480,10
           max   111 203 000,00 86 180 000,00 131 341 000,00 277 564 000,00
Employment count       1 514,00      1 514,00       1 513,00       1 515,00
           mean        1 569,02      1 601,85       1 765,88       1 652,75
           std         4 253,31      4 450,21       6 914,86       4 667,17
           min             1,00          1,00           1,00           1,00
           25%           250,25        251,75         260,00         266,50
           50%           569,00        564,04         568,00         573,00
           75%         1 338,00      1 350,75       1 374,00       1 352,50
           max        80 116,00     78 873,00     206 512,00      77 726,70

1515

Name          Orlen SA GK, Płock
Sales             277 564 000,00
Employment             64 494,00
Name: 0, dtype: object

Name          Firma Handlowa Rolnik sp.j., Mikołów
Sales                                   368 609,79
Employment                                  344,00
Name: 2033, dtype: object

                                             Name          Sales  Employment
0                              Orlen SA GK, Płock 277 564 000,00   64 494,00
1            Jeronimo Martins Polska SA, Kostrzyn  85 034 775,00   77 726,70
2     PGE Polska Grupa Energetyczna GK SA, Lublin  73 435 000,00   38 013,00
3  LG Energy Solution Wrocław sp. z o.o., Wrocław  40 736 584,00    7 154,00
4    Totalizator Sportowy sp. z o.o. GK, Warszawa  39 425 832,00    5 354,00

In [29]:
#ADDING ANALYSIS DIMENSIONS

# Polish / Foreign Ownership
# Create a copy of df_filter to avoid the SettingWithCopyWarning
df_filter = df_filter.copy()

# Polish / Foreign Companies
df_filter['P/F'] = np.where((df_filter['Owner Type'].astype(str).str[:1] == '5'), 'F', 'P')
df_filter['P/F'] = df_filter['P/F'].astype('category')

# High Internationalisation Export Sales > 25% of Sales
pivot_sales = df_filter.pivot(index='Name', columns='Year', values='Sales')

pivot_export_sales = df_filter.pivot(index='Name', columns='Year', values='Export Sales')

pivot_sales['Hint'] = (pivot_export_sales[2022] / pivot_sales[2022]) > 0.25
pivot_sales['Hint'] = pivot_sales['Hint'].apply(lambda x: 'Yes' if x else 'No')

df_filter = df_filter.merge(pivot_sales[['Hint']], on='Name')

In [30]:
# CLOSING CODES
df_filter.to_excel('2000 Analysis Students.xlsx', index=False)

print("DataFrame 'df_filter' has been saved to '2000 Analysis Students.xlsx'.")

DataFrame 'df_filter' has been saved to '2000 Analysis Students.xlsx'.