# DATA PREPARATION

In [12]:
# INITIATION: PYTHON AND DISPLAY

# Import libraries
import pandas as pd #
import numpy as np

# For better visibility
from IPython.display import display, HTML

# Apply a no-wrap style to prevent text wrapping
display(HTML("""
<style>
.dataframe td { white-space: nowrap; }
</style>
"""))

# Set the option to display all columns
pd.set_option('display.max_columns', None)

# Set the option to display all rows
pd.set_option('display.max_rows', None)

# Set the float format to use a space as a thousands separator and a comma as a decimal separator
pd.set_option('display.float_format', lambda x: f'{x:,.2f}'.replace(',', ' ').replace('.', ','))

In [13]:
# FILE LOAD and INTEGRATION

# Read the Excel file and specify that 'PKD' should be read as a string to preserve leading zeros
df = pd.read_excel('2000 Analysis Python.xlsx', decimal=',', dtype={'PKD': str})

pkd = pd.read_excel('2000 PKD.xlsx')  # Load the pkd data

# Convert 'PKD' to string and extract the first two characters (keeping leading zeros)
df['PKD_2'] = df['PKD'].astype(str).str.zfill(2).str[:2]

# Convert the 'PKD_2' column in pkd to a string to match the type of 'PKD'
pkd['PKD_2'] = pkd['PKD_2'].astype(str).str.zfill(2)

# Perform the merge using 'PKD' and 'Number'
df = pd.merge(
    df,
    pkd,
    left_on='PKD_2',
    right_on='PKD_2',
    how='left'
)

# Assign PKD_2 to the right place
cols = df.columns.tolist()

# Find current index of the column
current_index = cols.index('PKD_2')

# Calculate new index (2 positions to the right, but not beyond the end of the list)
new_index = min(current_index + 1, len(cols) - 1)

# Remove and re-insert at new position
cols.insert(new_index + 1, cols.pop(current_index))

# Reassign DataFrame with new column order
df = df[cols]

df.columns = df.columns.astype(str)

In [14]:
# FILE INSPECTION

# Print the number of rows and columns
print(f"Number of rows and columns: {df.shape}")

print("Number of companies = ", df[df['Year']==2023].shape[0])

# Display the first 5 rows of the DataFrame
display(df.head())

# Print the last 5 rows of the DataFrame
display(df.tail())

Number of rows and columns: (10000, 33)
Number of companies =  2000

,2023,2022,2021,2020,2019,Name,NIP,PKD,PKD Opis,Sector,Owner Type,Year,Sales,Profit from Operations,Profit after Financing,Net Profit,Depreciation,Export Sales,Employment,Staff costs,BS,Fixed Assets,Current Assets,Equity,Liabilities,Comments,Data Issues,Removal,PKD_1,PKD_1 Description,PKD_2,PKD_2 Description,Digital intensity
0,1,"1,00","1,00","1,00","1,00","Orlen SA GK, Płock",7740001454,1920,Wytwarzanie i przetwarzanie produktów rafinacj...,Oil,412,2023,372767000,"28 056 000,00",30314000,20727000,142000,102589000,66554,"11 175 000,00",264178000,170795000,93383000,153180000,"110 998 000,00",NaN,NaN,NaN,C,Manufacturing,19,MANUFACTURE AND PROCESSING OF COKE AND REFINED...,Medium-high
1,2,"2,00","3,00","2,00","2,00","Jeronimo Martins Polska SA, Kostrzyn",7791011327,4719,Pozostała sprzedaż detaliczna prowadzona w nie...,Retail,500,2023,98022928,"4 882 170,96","5 121 150,49","4 127 757,73","1 311 227,50",0,79292,"5 954 379,19","26 597 526,53","11 978 435,65","14 619 090,88",5299163,"21 298 363,10",NaN,NaN,NaN,G,Wholesale and Retail Trade; Repair of Motor Ve...,47,"RETAIL TRADE, EXCEPT OF MOTOR VEHICLES",Medium-high
2,3,"3,00","4,00","3,00","4,00","PGE Polska Grupa Energetyczna GK SA, Lublin",5260250541,7010,Działalność firm centralnych (head offices) i ...,Energy,145,2023,95964000,"-3 431 000,00",-4055000,-4902000,13455000,25000,42552,"6 287 000,00",113443000,78340000,35103000,47855000,"65 588 000,00",NaN,NaN,NaN,M,"Professional, Scientific and Technical Activities",70,ACTIVITIES OF HEAD OFFICES; MANAGEMENT CONSULT...,High
3,4,"5,00","11,00","17,00","30,00","Totalizator Sportowy sp. z o.o. GK, Warszawa",5250010982,9200,Działalność związana z grami losowymi i zakład...,Services,100,2023,52269058,"385 142,00",453419,362474,189397,0,5894,"786 162,00",2893324,1099674,1793650,1669328,"1 223 996,00",NaN,NaN,NaN,R,"Arts, Entertainment and Recreation",92,GAMBLING AND BETTING ACTIVITIES,Medium-high
4,5,"11,00","14,00","13,00","15,00","Enea SA GK, Poznań",7770020640,3514,Handel energią elektryczną,Energy,145,2023,48183419,"955 679,00",-508049,-442623,1651920,0,17853,"3 092 964,00",39110745,21636978,17473767,15439599,"23 671 146,00",NaN,NaN,NaN,D,"Electricity, Gas, Steam, Hot Water and Air Con...",35,"ELECTRICITY, GAS, STEAM, HOT WATER AND AIR CON...",Low

,2023,2022,2021,2020,2019,Name,NIP,PKD,PKD Opis,Sector,Owner Type,Year,Sales,Profit from Operations,Profit after Financing,Net Profit,Depreciation,Export Sales,Employment,Staff costs,BS,Fixed Assets,Current Assets,Equity,Liabilities,Comments,Data Issues,Removal,PKD_1,PKD_1 Description,PKD_2,PKD_2 Description,Digital intensity
9995,2,"2,00","3,00","2,00","2,00","Jeronimo Martins Polska SA, Kostrzyn",7791011327,4719,Pozostała sprzedaż detaliczna prowadzona w nie...,Retail,500,2019,"55 573 747,04","2 800 737,00",2733767,2241447,1052710,0,68159,"3 641 448,39",15387833,8356124,7031709,3469188,"11 918 644,11",NaN,NaN,NaN,G,Wholesale and Retail Trade; Repair of Motor Ve...,47,"RETAIL TRADE, EXCEPT OF MOTOR VEHICLES",Medium-high
9996,1,"1,00","1,00","1,00","1,00","Orlen SA GK, Płock",7740001454,1920,Wytwarzanie i przetwarzanie produktów rafinacj...,Oil,412,2019,111203000,"5 365 000,00",5352000,4298000,3497000,88962400,22337,"2 799 000,00",71202000,39277000,31925000,38607000,"32 595 000,00",NaN,NaN,NaN,C,Manufacturing,19,MANUFACTURE AND PROCESSING OF COKE AND REFINED...,Medium-high
9997,527,"474,00","853,00","884,00","897,00","Grupa FAKRO, Nowy Sącz",7341001487,4673,"Sprzedaż hurtowa drewna, materiałów budowlanyc...",Construction,450,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G,Wholesale and Retail Trade; Repair of Motor Ve...,46,"WHOLESALE TRADE, EXCEPT OF MOTOR VEHICLES",Medium-high
9998,1394,"1 531,00",NaN,NaN,NaN,"Pozkrone sp.c., Poznań",7831825830,4519,Sprzedaż hurtowa i detaliczna pozostałych poja...,Automotive,400,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G,Wholesale and Retail Trade; Repair of Motor Ve...,45,WHOLESALE AND RETAIL TRADE SERVICES OF MOTOR V...,Medium-high
9999,1599,"1 504,00",NaN,NaN,NaN,"Firma Kojs, Jabłonka",7351027264,1011,"Przetwarzanie i konserwowanie mięsa, z wyłącze...",Food,400,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C,Manufacturing,10,MANUFACTURE OF FOOD PRODUCTS,Low

In [4]:
# DATA CLEAN-UP

# Step 1: Identify duplicates based on 'Name' and 'Year' columns
duplicates = df[df.duplicated(subset=['Name', 'Year'], keep=False)]

# Step 2: Display the duplicates for inspection
print("Duplicate rows based on 'Name' and 'Year':")
print(duplicates)

Duplicate rows based on 'Name' and 'Year':
Empty DataFrame
Columns: [2023, 2022, 2021, 2020, 2019, Name, NIP, PKD, PKD Opis, Sector, Owner Type, Year, Sales, Profit from Operations, Profit after Financing, Net Profit, Depreciation, Export Sales, Employment, Staff costs, BS, Fixed Assets, Current Assets, Equity, Liabilities, PKD_2, Comments, Data Issues, Removal, PKD_1, PKD_1 Description, PKD_2 Description, Digital intensity]
Index: []

In [5]:
#DATA TYPES ASSIGNMENT

# Step 1: Changing data types for analysis
dtype_changes = {
    
    'PKD': 'category',
    'PKD_2': 'category',
    'PKD_1': 'category',
    'Sector': 'category',
    'Owner Type': 'category',
    'Year': 'category',
    'Sales': 'float',
    'Gross Profit': 'float',
    'Operating Profit': 'float',
    'Net Profit': 'float',
    'Depreciation': 'float',
    'Export Sales': 'float',
    'Employment': 'float',
    'Staff costs': 'float',
    'BS': 'float',
    'Operating Profit': 'float',
    'Fixed Assets': 'float',
    'Current Assets': 'float',
    'Equity': 'float',
    'Liabilities': 'float',
    'Digital intensity': 'category' 
    
    
    }
# Step 2: Check each column individually to identify possible issues

for col, dtype in dtype_changes.items():
    try:
        if dtype in ['float', 'int']:  # Check if the target type is numeric
            df[col] = pd.to_numeric(df[col], errors='coerce')  # Use pd.to_numeric for numeric conversion
        df[col] = df[col].astype(dtype)  # Convert to the target dtype
        print(f"Successfully converted {col} to {dtype}")
    except ValueError as e:
        print(f"Error converting {col} to {dtype}: {e}")

Successfully converted PKD to category
Successfully converted PKD_2 to category
Successfully converted PKD_1 to category
Successfully converted Sector to category
Successfully converted Owner Type to category
Successfully converted Year to category
Successfully converted Sales to float

KeyError: 'Gross Profit'

In [ ]:
display(df.info())

# ANALYSIS  SET-UP

In [ ]:
# SET THE TECHNICAL FILTERS

# Step 1: Identify companies with missing or zero Sales or Employment in 2019 or 2023
names_to_remove = df[
    (df['Year'].isin([2019, 2023])) & 
    (
        (df['Sales'] == 0) | pd.isnull(df['Sales']) |
        (df['Employment'] == 0) | pd.isnull(df['Employment'])
    )
]['Name'].unique()

# Step 2: Filter them out
df_filter = df[~df['Name'].isin(names_to_remove)]

# Step 3: Summary
print(f"Number of companies removed due to missing Sales or Employment in 2019 or 2023: {len(names_to_remove)}")

count_df = df[
    (df['Year'] == 2023)
].shape[0]
print("Number of companies in 2023 before filtering = ", count_df)

count_df_filter = df_filter[df_filter['Year'] == 2023].shape[0]
print("Number of companies in 2023 after filtering = ", count_df_filter)

In [ ]:
#Lista firm usuniętych z analizy
df_print = df[df['Name'].isin(names_to_remove)]

display(df_print.pivot(index='Name', columns='Year', values='Employment'))

In [ ]:
#CHECK OF FILTERING

# Select the columns you want to include in the groupby and describe operations
selected_columns = ['Sales', 'Employment']

# Group by Year' and apply describe to the selected columns only
df_summary = df.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
df_filter_summary = df_filter.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
display(df_summary, df_filter_summary)

# Show max and min company
selected_columns = ['Name','Sales', 'Employment']
display(df_filter['Name'].nunique())
display(df_filter.loc[df_filter['Sales'].idxmax(),selected_columns])
display(df_filter.loc[df_filter[df_filter['Year'] == 2023]['Sales'].idxmin(),selected_columns])

display(df_filter[selected_columns].head())

display(df_filter[selected_columns].tail())

In [ ]:
#ADDING DESCRIPTIVE ANALYSIS DIMENSIONS

# Create a copy of df_filter to avoid the SettingWithCopyWarning
df_filter = df_filter.copy()

#Export as % of Sales
df_filter['Export as % of Sales']= df_filter['Export Sales'] / df_filter['Sales'] *100

#ROA / ROS / ROE
df_filter['ROS']= df_filter['Net Profit'] / df_filter['Sales']
df_filter['ROA']= df_filter['Net Profit'] / df_filter['BS']  
df_filter['ROE']= df_filter['Net Profit'] / df_filter['Equity']

# Polish / Foreign Companies
df_filter['P/F'] = np.where((df_filter['Owner Type'].astype(str).str[:1] == '5'), 'F', 'P')
df_filter['P/F'] = df_filter['P/F'].astype('category')

# BalanceSheet Strength - Equity / BS
df_filter['BS'] = df_filter['BS'].replace(0, np.nan) # Replace 0 in the BS column with NaN to avoid division by zero
df_filter['BS_Strength'] = df_filter['Equity'] / df_filter['BS']

# Human Capital Proxy - Staff costs / employment
df_filter['Human_Capital'] = df_filter['Staff costs'] / df_filter['Employment']

# GVA (Gross Profit + Staff Costs)
df_filter['GVA']=df_filter['Gross Profit'] + df_filter['Staff costs']

# Productivity
df_filter['Productivity']=df_filter['GVA'] / df_filter['Employment']

In [ ]:
#SALES & PROFITABILITY STATISTICS

# Isolate the annual growth rate threshold
inflation = 8.5 # (38,5% inflation between 2019 and 2023 - 3,4%	5,1%	14,4%	11,4%)
stability_threshold = 10 #(97,2% of nominal compound growth between 2019 and 2023)
growth_threshold = 20 #(172,8% of nominal compound growth between 2019 and 2023)

# Pivot the DataFrame to make year-based comparison easier for both Sales and Export
#(use only with 2023 set as a filter)
pivot_sales = df_filter.pivot(index='Name', columns='Year', values='Sales')
pivot_export_sales = df_filter.pivot(index='Name', columns='Year', values='Export Sales')
pivot_gva = df_filter.pivot(index='Name', columns='Year', values='GVA')

# High Internationalisation Export Sales > 25% of Sales
pivot_sales['Hint25'] = (pivot_export_sales[2023] / pivot_sales[2023]) > 0.25
pivot_sales['Hint25'] = pivot_sales['Hint25'].apply(lambda x: 'Exp>25' if x else 'Exp<25')

# High Internationalisation Export Sales > 50% of Sales
pivot_sales['Hint50'] = (pivot_export_sales[2023] / pivot_sales[2023]) > 0.50
pivot_sales['Hint50'] = pivot_sales['Hint50'].apply(lambda x: 'Exp>50' if x else 'Exp<50')

# HGX Export Driven
pivot_sales['HGX'] = (pivot_export_sales[2023] / pivot_sales[2023]) > (pivot_export_sales[2019] / pivot_sales[2019])
pivot_sales['HGX'] = pivot_sales['HGX'].apply(lambda x: 'Increased Export Intensity' if x else 'Decreased Export Intensity')

# HGX Export Driven
pivot_sales['HGX%'] = pivot_export_sales[2023] / pivot_sales[2023] - pivot_export_sales[2019] / pivot_sales[2019]


# Sales Growth_2023_2019 (Total and Annualised Growth)
pivot_sales['SGrowth_2023_2019'] = (pivot_sales[2023] - pivot_sales[2019]) / pivot_sales[2019] * 100
pivot_sales['Annualised_Growth'] = ((pivot_sales[2023] / pivot_sales[2019]) ** (1/4) - 1) * 100
# Sales Growth 2023_2019 - ln transformation
pivot_sales['LSGrowth_2023_2019'] = np.log(pivot_sales[2023]) - np.log(pivot_sales[2019])

pivot_sales['RealSales_2023'] = pivot_sales[2023] / 1.38
pivot_sales['RSGrowth_2023_2019'] = ((pivot_sales[2023] / 1.38) - pivot_sales[2019]) / pivot_sales[2019] * 100
pivot_sales['LRSGrowth_2023_2019'] = np.log(pivot_sales['RealSales_2023']) - np.log(pivot_sales[2019])

# Sales Drop Conditions

pivot_sales['Drop_Sales_2020'] = (pivot_sales[2020]/(1+0.034) < pivot_sales[2019])
pivot_sales['Drop_Sales_2020'] = pivot_sales['Drop_Sales_2020'].apply(lambda x: 'Yes' if x else 'No')

pivot_sales['Drop_Sales_2023'] = (pivot_sales[2023]/(1+0.114) < pivot_sales[2022])
pivot_sales['Drop_Sales_2023'] = pivot_sales['Drop_Sales_2023'].apply(lambda x: 'Yes' if x else 'No')

pivot_sales['Drop_Sales_Both'] = (pivot_sales[2023]/(1+0.114) < pivot_sales[2022]) & (pivot_sales[2020]/(1+0.034) < pivot_sales[2019])
pivot_sales['Drop_Sales_Both'] = pivot_sales['Drop_Sales_Both'].apply(lambda x: 'Yes' if x else 'No')


# GVA Growth_2023_2019 (in PLN)
pivot_gva['GVAGrowth_2023_2019'] = (pivot_gva[2023] - pivot_gva[2019])


# Add Growth column with 3 growth categories
def categorize_growth(row):
    if row['Annualised_Growth'] > (growth_threshold + inflation):
        return '3.Very High'
    elif (stability_threshold + inflation) < row['Annualised_Growth'] <= (growth_threshold + inflation):
        return '2.High'
    elif inflation < row['Annualised_Growth'] <= (stability_threshold + inflation):
        return '1.Moderate'
    else:
        return '0.Below Inflation'

pivot_sales['SGrowth_3'] = pivot_sales.apply(categorize_growth, axis=1)

# Add # Add Growth column with 2 growth categories
def categorize_growth1(row):
    if row['Annualised_Growth'] > (growth_threshold):
        return '3.High Growth'
    elif inflation <= row['Annualised_Growth'] <= (growth_threshold):
        return '2.Stable'
    elif 0 < row['Annualised_Growth'] <= inflation:
        return '1.Declining'
    else:
        return '0.Stressed'             

pivot_sales['SGrowth_2'] = pivot_sales.apply(categorize_growth1, axis=1)

# Add # Add Growth column with 1 growth category
def categorize_growth2(row):
    if row['Annualised_Growth'] > (inflation):
        return 'Growing'
    else:
        return 'Declining'
pivot_sales['SGrowth_1'] = pivot_sales.apply(categorize_growth2, axis=1)

# Merge the calculated columns back to the original df_filter DataFrame
df_filter = df_filter.merge(pivot_sales[['Hint25','Hint50','HGX','HGX%','SGrowth_2023_2019','LSGrowth_2023_2019','RSGrowth_2023_2019','LRSGrowth_2023_2019','Annualised_Growth', 'Drop_Sales_2020', 'Drop_Sales_2023','Drop_Sales_Both','SGrowth_3','SGrowth_2','SGrowth_1']], on='Name')
df_filter = df_filter.merge(pivot_gva['GVAGrowth_2023_2019'], on='Name')

In [ ]:
#EMPLOYMENT STATISTICS

# Pivot the DataFrame to make year-based comparison easier for Employment
#(use only with 2023 set as a filter)
pivot_employment = df_filter.pivot(index='Name', columns='Year', values='Employment')
pivot_productivity = df_filter.pivot(index='Name',columns='Year',values='Productivity')

# Calculate Employment Growth_2023_2019 (Total Growth)
pivot_employment['EGrowth_2023_2019'] = (pivot_employment[2023] - pivot_employment[2019]) / pivot_employment[2019] * 100
# Employment Growth (Percentage) - ln transformation
pivot_employment['LEGrowth_2023_2019'] = np.log(pivot_employment[2023]) - np.log(pivot_employment[2019])

pivot_employment['Annualised_EGrowth'] = ((pivot_employment[2023] / pivot_employment[2019]) ** (1/4) - 1) * 100

# Calculate Productivity Growth_2023_2019 (Total Growth)
pivot_productivity['PGrowth_2023_2019'] = pivot_productivity[2023] - pivot_productivity[2019]


# Add Growth column with 3 categories
def categorize_egrowth(row):
    if row['EGrowth_2023_2019'] < 0:
        return '0.Reducing'
    elif (0) < row['Annualised_EGrowth'] <= (1.10):
        return '1.Sustaining'
    else:
        return '2.Hiring'

pivot_employment['EGrowth_3'] = pivot_employment.apply(categorize_egrowth, axis=1)

# Add Growth column with 2 categories
def categorize_egrowth1(row):
    if row['EGrowth_2023_2019'] < 0:
        return 'Reducing'
    else:
        return 'Hiring'

pivot_employment['EGrowth_2'] = pivot_employment.apply(categorize_egrowth1, axis=1)
    
# Calculate Employment Drop conditions
#pivot_employment['Drop_Employment'] = (pivot_employment[2020] < pivot_employment[2019]) | (pivot_employment[2021] < pivot_employment[2020]) | (pivot_employment[2022] < pivot_employment[2021]) | (pivot_employment[2023] < pivot_employment[2022])
pivot_employment['Drop_Employment'] = (pivot_employment[2020] < pivot_employment[2019])
pivot_employment['Drop_Employment'] = pivot_employment['Drop_Employment'].apply(lambda x: 'Yes' if x else 'No')

# Step 5: Merge the calculated columns back to the original df_filter DataFrame
df_filter = df_filter.merge(pivot_employment[['EGrowth_2023_2019','LEGrowth_2023_2019','Annualised_EGrowth','Drop_Employment','EGrowth_3','EGrowth_2']], on='Name')
df_filter = df_filter.merge(pivot_productivity['PGrowth_2023_2019'], on='Name')

In [ ]:
#ADDING ADDITIONAL REGRESSION ANALYSIS DIMENSIONS

#np.arcsinh() used for all variables because it handles negative 
#zero, and positive values consistently, compresses outliers effectively,
#and ensures robustness across your regression analysis.
#arcsinh(x)=ln(x+ squared root(x^2+1))


# Starting Profit - ROS in 2019
ros_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['ROS'] # Step 1: Extract 2019 ROS values
df_filter['Starting_Profit'] = df_filter['Name'].map(ros_2019)# Step 2: Map 2019 ROS values to the 'Starting_Profit' column for all rows

# Starting Internationalisation level - #Export as % of Sales in 2019
Starting_INT = df_filter[df_filter['Year'] == 2019].set_index('Name')['Export as % of Sales'] # Step 1: Extract 2019 Export as % of Sales values
df_filter['Starting_INT'] = df_filter['Name'].map(Starting_INT)# Step 2: Map 2019 Export as % values to the 'Starting_INT' column for all rows

#Starting BS Strength
bs_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['BS_Strength'] # Step 1: Extract 2019 BS_Strength values
df_filter['Starting_BS_Strength'] = df_filter['Name'].map(bs_2019)# Step 2: Map 2019 ROS values to the 'Starting_Profit' column for all rows

# Starting Size - natural log of Sales for 2019
ln_sales_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Sales'].apply(np.log)
df_filter['Starting_Size_ln'] = df_filter['Name'].map(ln_sales_2019)  # Step 2: Map these values to the 'Starting_Size' column

#Starting HC Strength
hc_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Human_Capital']
df_filter['Starting_Human_Capital']=df_filter['Name'].map(hc_2019)

# Starting GVA - GVA in 2019
gva_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['GVA'] # Step 1: Extract 2019 GVA values
df_filter['Starting_GVA'] = df_filter['Name'].map(gva_2019)# Step 2: Map 2019 GVA values to the 'Starting_GVA' column for all rows

# Starting Productivity - Productivity in 2019
productivity_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Productivity'] # Step 1: Extract 2019 Productivity values
df_filter['Starting_Prod'] = df_filter['Name'].map(productivity_2019)# Step 2: Map 2019 Productivity values to the 'Starting_Prod' column for all rows


#OPTIONAL arcsinh calculations

# Starting Size - arcsinh sales in 2019
#arcsinh_sales_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Sales'].apply(np.arcsinh)  # Step 1: Calculate arcsinh(Sales) for 2019
#f_filter['Starting_Size_arc'] = df_filter['Name'].map(arcsinh_sales_2019)  # Step 2: Map these values to the 'Starting_Size' column


# Sales Growth (Percentage) - arcsinh transformation
#df_filter['ASGrowth_2023_2019'] = np.arcsinh(df_filter['SGrowth_2023_2019'] / 100)

# Real Sales Growth (Percentage) - arcsinh transformation
#df_filter['ARSGrowth_2023_2019'] = np.arcsinh(df_filter['RSGrowth_2023_2019'] / 100)

# Employment Growth (Percentage) - arcsinh transformation
#df_filter['AEGrowth_2023_2019'] = np.arcsinh(df_filter['EGrowth_2023_2019'] / 100)

# GVA Growth (Nominal PLN) - arcsinh transformation
#df_filter['AGVAGrowth_2023_2019'] = np.arcsinh(df_filter['GVAGrowth_2023_2019'])

# Productivity Growth (Nominal PLN) - arcsinh transformation
#df_filter['APGrowth_2023_2019'] = np.arcsinh(df_filter['PGrowth_2023_2019'])

In [ ]:
# Filter for year 2023 and get top 10 by sales growth
top_10_growth_2023 = df_filter[df_filter['Year'] == 2023][['Name', 'SGrowth_2023_2019']]\
    .sort_values(by='SGrowth_2023_2019', ascending=False).head(10)

# Correct: Sort ascending to get bottom 10
bottom_10_growth_2023 = df_filter[df_filter['Year'] == 2023][['Name', 'SGrowth_2023_2019']]\
    .sort_values(by='SGrowth_2023_2019', ascending=True).head(10)

display(top_10_growth_2023)

display(bottom_10_growth_2023)


# DATA WITH COMMENTS
df_filter.to_excel('2000 Analysis Python CALCULATED.xlsx', index=False)

print("DataFrame 'df_filter' has been saved to '2000 Analysis Python CALCULATED.xlsx'.")

In [ ]:
# SET THE ANALYTICAL FILTERS

# Identify names with outlier Export as % of Sales
names_to_remove = df_filter[
    (df_filter['Year'].isin([2019, 2023])) & 
    (df_filter['Export as % of Sales'] > 100)
]['Name'].unique()

# Remove those companies + those not present in 2019 list
df_filter = df_filter[
    df_filter['2019'].notna() & (~df_filter['Name'].isin(names_to_remove))
]

# Optional filter: remove fuel sector companies (PKD_2 == '19')
# Uncomment next line to activate
# company_filter = df_filter[df_filter['PKD_2'] == '19']

if 'company_filter' in locals():
    df_filter = df_filter[~df_filter.index.isin(company_filter.index)]
    num_sector_removed = company_filter['Name'].nunique()
else:
    num_sector_removed = 0

# Show results
print(f"Number of companies removed due to sector considerations: {num_sector_removed}")
print(f"Number of companies removed due to Export as % of Sales > 100 in 2019 or 2023: {len(names_to_remove)}")

count_df = df[
    (df['2023'] != 0) & (df['2023'].notna()) & 
    (df['2019'] != 0) & (df['2019'].notna()) & 
    (df['Year'] == 2023)
].shape[0]
print("Number of companies from 2019 list before filtering = ", count_df)

count_df_filter = df_filter[df_filter['Year'] == 2023].shape[0]
print("Number of companies from 2019 list after filtering = ", count_df_filter)

In [ ]:
#CHECK OF FILTERING

# Select the columns you want to include in the groupby and describe operations
selected_columns = ['Sales']

# Group by Year' and apply describe to the selected columns only
df_summary = df.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
df_filter_summary = df_filter.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
display(df_summary, df_filter_summary)

# Show max and min company
selected_columns = ['Name','Sales', 'Employment']
display(df_filter['Name'].nunique())
display(df_filter.loc[df_filter['Sales'].idxmax(),selected_columns])
display(df_filter.loc[df_filter[df_filter['Year'] == 2023]['Sales'].idxmin(),selected_columns])

display(df_filter[selected_columns].head())

display(df_filter[selected_columns].tail())

In [ ]:
# CLOSING CODES
df_filter.to_excel('2000 Analysis Python CHANGED.xlsx', index=False)

print("DataFrame 'df_filter' has been saved to '2000 Analysis Python CHANGED.xlsx'.")

In [ ]:
df_summary = df_filter.groupby(['Year'], observed=False)[['Sales','Employment']].describe().transpose()

display(df_summary)

df_summary.to_excel('Results/Summary Stats.xlsx', index=True)

In [ ]:
# Filter for 2023
df_2023 = df_filter[df_filter['Year'] == 2023]

# Choose variables to summarize
columns_of_interest = ['LSGrowth_2023_2019','Starting_INT', 'Starting_BS_Strength','Starting_Size_ln', 'Starting_Profit',
                      'HGX%']  # add more if needed

# Compute and transpose the summary
df_summary_2023 = df_2023[columns_of_interest].describe().transpose()

# Display and export
display(df_summary_2023.T)
df_summary_2023.T.to_excel('Results/Summary Stats 2023.xlsx')