# DATA PREPARATION

In [1]:
# INITIATION: PYTHON AND DISPLAY

# Import libraries
import pandas as pd #
import numpy as np

# For better visibility
from IPython.display import display, HTML

# Apply a no-wrap style to prevent text wrapping
display(HTML("""
<style>
.dataframe td { white-space: nowrap; }
</style>
"""))

# Set the option to display all columns
pd.set_option('display.max_columns', None)

# Set the option to display all rows
pd.set_option('display.max_rows', None)

# Set the float format to use a space as a thousands separator and a comma as a decimal separator
pd.set_option('display.float_format', lambda x: f'{x:,.2f}'.replace(',', ' ').replace('.', ','))

In [2]:
# FILE LOAD and INTEGRATION

# Read the Excel file and specify that 'PKD' should be read as a string to preserve leading zeros
df = pd.read_excel('2000 Analysis Python.xlsx', decimal=',', dtype={'PKD': str})

pkd = pd.read_excel('2000 PKD.xlsx')  # Load the pkd data

# Convert 'PKD' to string and extract the first two characters (keeping leading zeros)
df['PKD_2'] = df['PKD'].astype(str).str.zfill(2).str[:2]

# Convert the 'PKD_2' column in pkd to a string to match the type of 'PKD'
pkd['PKD_2'] = pkd['PKD_2'].astype(str).str.zfill(2)

# Perform the merge using 'PKD' and 'Number'
df = pd.merge(
    df,
    pkd,
    left_on='PKD_2',
    right_on='PKD_2',
    how='left'
)

# Assign PKD_2 to the right place
cols = df.columns.tolist()

# Find current index of the column
current_index = cols.index('PKD_2')

# Calculate new index (2 positions to the right, but not beyond the end of the list)
new_index = min(current_index + 1, len(cols) - 1)

# Remove and re-insert at new position
cols.insert(new_index + 1, cols.pop(current_index))

# Reassign DataFrame with new column order
df = df[cols]

df.columns = df.columns.astype(str)

In [3]:
# FILE INSPECTION

# Print the number of rows and columns
print(f"Number of rows and columns: {df.shape}")

print("Number of companies = ", df[df['Year']==2023].shape[0])

# Display the first 5 rows of the DataFrame
display(df.head())

# Print the last 5 rows of the DataFrame
display(df.tail())

Number of rows and columns: (9380, 43)
Number of companies =  1876

,2023,2022,2021,2020,2019,Name,GPW,Age (KRS),Business age,Business age?,Foreign branches,REGON,KRS,NIP,Legal form,PKD,PKD Opis,Sector 500,Sector,Country,Owner Type,S/J,Year,Sales,Gross Profit,Operating Profit,Net Profit,Depreciation,Export Sales,Employment,Staff costs,BS,Fixed Assets,Current Assets,Equity,Liabilities,Remove,Comments,PKD_1,PKD_1 Description,PKD_2,PKD_2 Description,Digital intensity
0,"1,00","1,00","1,00","1,00",1,"Orlen SA GK, Płock",SG),1999,"1 944,00","2 001,00",Tak,610188201,28860,7740001454,SA,1920,Wytwarzanie i przetwarzanie produktów rafinacj...,Prod. paliw i energii,paliwa,NaN,412,S,2020,"86 180 000,00","3 908 000,00",2856000,"2 825 000,00",4537000,73379000,33377,"3 783 000,00",83827000,59212000,24615000,42379000,41448000,NaN,NaN,C,Manufacturing,19,MANUFACTURE AND PROCESSING OF COKE AND REFINED...,Medium-high
1,"1,00","1,00","1,00","1,00",1,"Orlen SA GK, Płock",SG),1999,"1 944,00","2 001,00",Tak,610188201,28860,7740001454,SA,1920,Wytwarzanie i przetwarzanie produktów rafinacj...,Prod. paliw i energii,paliwa,NaN,412,S,2019,"111 203 000,00","5 365 000,00",5352000,"4 298 000,00",3497000,88962400,22337,"2 799 000,00",71202000,39277000,31925000,38607000,32595000,NaN,NaN,C,Manufacturing,19,MANUFACTURE AND PROCESSING OF COKE AND REFINED...,Medium-high
2,"1,00","1,00","1,00","1,00",1,"Orlen SA GK, Płock",SG),1999,"1 944,00","2 001,00",Tak,610188201,28860,7740001454,SA,1920,Wytwarzanie i przetwarzanie produktów rafinacj...,Prod. paliw i energii,paliwa,NaN,412,S,2021,"131 341 000,00","13 870 000,00",13683000,"11 188 000,00",5341000,114100000,35424,"4 602 000,00",106754000,68706000,38048000,52578000,54176000,NaN,NaN,C,Manufacturing,19,MANUFACTURE AND PROCESSING OF COKE AND REFINED...,Medium-high
3,"1,00","1,00","1,00","1,00",1,"Orlen SA GK, Płock",SG),1999,"1 944,00","2 001,00",Tak,610188201,28860,7740001454,SA,1920,Wytwarzanie i przetwarzanie produktów rafinacj...,Prod. paliw i energii,paliwa,NaN,412,S,2022,"282 415 000,00","48 350 000,00",47350000,"39 819 000,00",7724000,114120000,64494,"6 928 000,00",272327000,174379000,138798000,143110000,170067000,NaN,NaN,C,Manufacturing,19,MANUFACTURE AND PROCESSING OF COKE AND REFINED...,Medium-high
4,"1,00","1,00","1,00","1,00",1,"Orlen SA GK, Płock",SG),1999,"1 944,00","2 001,00",Tak,610188201,28860,7740001454,SA,1920,Wytwarzanie i przetwarzanie produktów rafinacj...,Prod. paliw i energii,paliwa,NaN,412,S,2023,"371 916 000,00","31 321 000,00",30563000,"20 969 000,00",14193000,101739000,66554,"11 175 000,00",264463000,181265000,83198000,153420000,111043000,"1,00",Merger,C,Manufacturing,19,MANUFACTURE AND PROCESSING OF COKE AND REFINED...,Medium-high

,2023,2022,2021,2020,2019,Name,GPW,Age (KRS),Business age,Business age?,Foreign branches,REGON,KRS,NIP,Legal form,PKD,PKD Opis,Sector 500,Sector,Country,Owner Type,S/J,Year,Sales,Gross Profit,Operating Profit,Net Profit,Depreciation,Export Sales,Employment,Staff costs,BS,Fixed Assets,Current Assets,Equity,Liabilities,Remove,Comments,PKD_1,PKD_1 Description,PKD_2,PKD_2 Description,Digital intensity
9375,"1 941,00",NaN,NaN,NaN,2000,"Intermeble sp. z o.o. sp.k., Poznań",NaN,NaN,NaN,"2 008,00",NaN,300737027,995813,6652851796,sp. z o.o.,3109,Produkcja pozostałych mebli,NaN,produkcja,NaN,400,J,2022,"65 528,83","2 081,62","14 586,84","13 963,92","2 618,78",45322,484,"5 461,71","238 125,33","93 309,00","144 816,33","81 453,63","156 671,71",NaN,NaN,C,Manufacturing,31,MANUFACTURE OF FURNITURE,Medium-high
9376,"1 941,00",NaN,NaN,NaN,2000,"Intermeble sp. z o.o. sp.k., Poznań",NaN,NaN,NaN,"2 008,00",NaN,300737027,995813,6652851796,sp. z o.o.,3109,Produkcja pozostałych mebli,NaN,produkcja,NaN,400,J,2019,"286 980,00","30 455,00",26437,"26 437,00",15629,NaN,516,"27 336,00",207144,134412,72732,88329,118815,NaN,NaN,C,Manufacturing,31,MANUFACTURE OF FURNITURE,Medium-high
9377,"1 941,00",NaN,NaN,NaN,2000,"Intermeble sp. z o.o. sp.k., Poznań",NaN,NaN,NaN,"2 008,00",NaN,300737027,995813,6652851796,sp. z o.o.,3109,Produkcja pozostałych mebli,NaN,produkcja,NaN,400,J,2020,"290 192,76","39 868,02","24 576,52","24 576,52","15 740,69",NaN,NaN,NaN,"202 468,81","105 242,31","97 226,51","67 980,75","134 488,06",NaN,NaN,C,Manufacturing,31,MANUFACTURE OF FURNITURE,Medium-high
9378,"1 941,00",NaN,NaN,NaN,2000,"Intermeble sp. z o.o. sp.k., Poznań",NaN,NaN,NaN,"2 008,00",NaN,300737027,995813,6652851796,sp. z o.o.,3109,Produkcja pozostałych mebli,NaN,produkcja,NaN,400,J,2021,"378 127,93","55 881,92","47 709,06","41 467,60","14 341,52",188253,480,"32 880,39","213 814,16","98 907,67","114 906,49","22 962,21","190 851,95",NaN,NaN,C,Manufacturing,31,MANUFACTURE OF FURNITURE,Medium-high
9379,"1 941,00",NaN,NaN,NaN,2000,"Intermeble sp. z o.o. sp.k., Poznań",NaN,NaN,NaN,"2 008,00",NaN,300737027,995813,6652851796,sp. z o.o.,3109,Produkcja pozostałych mebli,NaN,produkcja,NaN,400,J,2023,"414 612,29","31 317,07","39 563,82","36 444,00","15 886,32",309646,473,"40 050,15","221 440,74","89 932,01","131 508,73","110 182,49","111 258,25",NaN,NaN,C,Manufacturing,31,MANUFACTURE OF FURNITURE,Medium-high

In [4]:
# DATA CLEAN-UP

# Step 1: Identify duplicates based on 'Name' and 'Year' columns
duplicates = df[df.duplicated(subset=['Name', 'Year'], keep=False)]

# Step 2: Display the duplicates for inspection
print("Duplicate rows based on 'Name' and 'Year':")
print(duplicates)

Duplicate rows based on 'Name' and 'Year':
Empty DataFrame
Columns: [2023, 2022, 2021, 2020, 2019, Name, GPW, Age (KRS), Business age, Business age?, Foreign branches, REGON, KRS, NIP, Legal form, PKD, PKD Opis, Sector 500, Sector, Country, Owner Type, S/J, Year, Sales, Gross Profit, Operating Profit, Net Profit, Depreciation, Export Sales, Employment, Staff costs, BS, Fixed Assets, Current Assets, Equity, Liabilities, Remove, Comments, PKD_1, PKD_1 Description, PKD_2, PKD_2 Description, Digital intensity]
Index: []

In [5]:
#DATA TYPES ASSIGNMENT

# Step 1: Changing data types for analysis
dtype_changes = {
    '2019': 'Int64',
    '2020': 'Int64',
    '2021': 'Int64',
    '2022': 'Int64',
    '2023': 'Int64',
    'PKD': 'category',
    'PKD_2': 'category',
    'PKD_1': 'category',
    'Sector': 'category',
    'Owner Type': 'category',
    'Year': 'category',
    'Sales': 'float',
    'Gross Profit': 'float',
    'Operating Profit': 'float',
    'Net Profit': 'float',
    'Depreciation': 'float',
    'Export Sales': 'float',
    'Employment': 'float',
    'Staff costs': 'float',
    'BS': 'float',
    'Operating Profit': 'float',
    'Fixed Assets': 'float',
    'Current Assets': 'float',
    'Equity': 'float',
    'Liabilities': 'float',
    'Digital intensity': 'category' 
    
    
    }
# Step 2: Check each column individually to identify possible issues

for col, dtype in dtype_changes.items():
    try:
        if dtype in ['float', 'int']:  # Check if the target type is numeric
            df[col] = pd.to_numeric(df[col], errors='coerce')  # Use pd.to_numeric for numeric conversion
        df[col] = df[col].astype(dtype)  # Convert to the target dtype
        print(f"Successfully converted {col} to {dtype}")
    except ValueError as e:
        print(f"Error converting {col} to {dtype}: {e}")

Successfully converted 2019 to Int64
Successfully converted 2020 to Int64
Successfully converted 2021 to Int64
Successfully converted 2022 to Int64
Successfully converted 2023 to Int64
Successfully converted PKD to category
Successfully converted PKD_2 to category
Successfully converted PKD_1 to category
Successfully converted Sector to category
Successfully converted Owner Type to category
Successfully converted Year to category
Successfully converted Sales to float
Successfully converted Gross Profit to float
Successfully converted Operating Profit to float
Successfully converted Net Profit to float
Successfully converted Depreciation to float
Successfully converted Export Sales to float
Successfully converted Employment to float
Successfully converted Staff costs to float
Successfully converted BS to float
Successfully converted Fixed Assets to float
Successfully converted Current Assets to float
Successfully converted Equity to float
Successfully converted Liabilities to float
Successfully converted Digital intensity to category

In [6]:
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 43 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   2023               7690 non-null   Int64
 1   2022               7580 non-null   Int64
 2   2021               7685 non-null   Int64
 3   2020               8235 non-null   Int64
 4   2019               9380 non-null   Int64
 5   Name               9380 non-null   object
 6   GPW                715 non-null    object
 7   Age (KRS)          2090 non-null   object
 8   Business age       400 non-null    float64
 9   Business age?      6895 non-null   float64
 10  Foreign branches   15 non-null     object
 11  REGON              9375 non-null   object
 12  KRS                9380 non-null   int64
 13  NIP                9380 non-null   int64
 14  Legal form         9375 non-null   object
 15  PKD                9380 non-null   category
 16  PKD Opis           9380 non-null   object
 17  Sector 500         2105 non-null   object
 18  Sector             9380 non-null   category
 19  Country            330 non-null    object
 20  Owner Type         9380 non-null   category
 21  S/J                9375 non-null   object
 22  Year               9380 non-null   category
 23  Sales              9377 non-null   float64
 24  Gross Profit       9336 non-null   float64
 25  Operating Profit   9333 non-null   float64
 26  Net Profit         9340 non-null   float64
 27  Depreciation       9323 non-null   float64
 28  Export Sales       9284 non-null   float64
 29  Employment         9279 non-null   float64
 30  Staff costs        9296 non-null   float64
 31  BS                 9329 non-null   float64
 32  Fixed Assets       9325 non-null   float64
 33  Current Assets     9324 non-null   float64
 34  Equity             9329 non-null   float64
 35  Liabilities        9329 non-null   float64
 36  Remove             23 non-null     float64
 37  Comments           24 non-null     object
 38  PKD_1              9380 non-null   category
 39  PKD_1 Description  9380 non-null   object
 40  PKD_2              9380 non-null   category
 41  PKD_2 Description  9380 non-null   object
 42  Digital intensity  9380 non-null   category
dtypes: Int64(5), category(7), float64(16), int64(2), object(13)
memory usage: 2.7+ MB

None

# ANALYSIS  SET-UP

In [7]:
# SET THE TECHNICAL FILTERS

# Step 1: Identify companies with missing or zero Sales or Employment in 2019 or 2023
names_to_remove = df[
    (df['Year'].isin([2019, 2023])) & 
    (
        (df['Sales'] <= 0) | pd.isnull(df['Sales']) |
        (df['Employment'] <= 0) | pd.isnull(df['Employment'])
    )
]['Name'].unique()

# Step 2: Filter them out
df_filter = df[~df['Name'].isin(names_to_remove)]

# Step 3: Summary
print(f"Number of companies removed due to missing Sales or Employment in 2019 or 2023: {len(names_to_remove)}")

count_df = df[
    (df['Year'] == 2023)
].shape[0]
print("Number of companies in 2023 before filtering = ", count_df)

count_df_filter = df_filter[df_filter['Year'] == 2023].shape[0]
print("Number of companies in 2023 after filtering = ", count_df_filter)

Number of companies removed due to missing Sales or Employment in 2019 or 2023: 62
Number of companies in 2023 before filtering =  1876
Number of companies in 2023 after filtering =  1814

In [8]:
#Lista firm usuniętych z analizy
df_print = df[df['Name'].isin(names_to_remove)]

display(df_print.pivot(index='Name', columns='Year', values='Employment'))

Year,2019,2020,2021,2022,2023
Name,,,,,
"Accenture sp. z o.o. GK, Warszawa","0,00","0,00","7 809,00","7 809,00","8 261,00"
"Aldesa Nowa Energia sp. z o.o., Warszawa","31,00","48,00","30,00","8,60","0,00"
"Animex K4 sp. z o.o., Warszawa","759,00","834,00","0,00","0,00","0,00"
"Auto Special SA sp.a.k., Kraków","346,00","245,50","0,00","0,00","0,00"
"BM Reflex sp. z o.o. sp.k., Łódź",NaN,"0,00","0,00","0,00","0,00"
"Beloil Polska sp. z o.o., Warszawa","24,00","24,00","23,00","7,00","1,00"
"British Automotive Centrum sp. z o.o., Warszawa (w upadłości)","63,00","56,00","55,00","0,00","0,00"
"Ceetrus Polska sp. z o.o., Warszawa","76,00",NaN,"0,00","0,00","0,00"
Citronex Mop sp. z o.o. sp.k.,"176,00",NaN,NaN,NaN,NaN
"Coral Travel Poland sp. z o.o., Warszawa","0,00","0,00","307,00","331,00","392,00"
Dowhan sp. z o.o.,"16,00","0,00","0,00","0,00","0,00"
"EP Resources PL SA, Katowice",NaN,NaN,NaN,NaN,NaN
"EPAM Systems (Poland) sp. z o.o., Warszawa",NaN,NaN,"2 616,00","4 771,00","6 174,00"
"Elektrix SA, Warszaw",NaN,NaN,NaN,NaN,NaN
"Global Business Travel Poland SA, Warszawa",NaN,NaN,NaN,"310,00","363,00"
"Grupa FAKRO, Nowy Sącz",NaN,NaN,NaN,NaN,NaN
"Grupa P4 sp. z o.o., Warszawa",NaN,NaN,"2 600,00","2 672,00",NaN
"Grupa Producentów Drobiu sp. z o.o., Bolesławiec",NaN,NaN,NaN,NaN,"70,00"
"Grupa Saint-Gobain w Polsce, Dąbrowa Górnicza","7 455,00","7 207,00","7 100,00","6 907,00",NaN
"HUAWEI Polska sp. z o.o., Warszawa",NaN,NaN,NaN,"216,00","211,00"
"I-Coal sp. z o.o., Katowice","5,00","0,00","0,00","0,00","0,00"
"INPOST sp. z o.o., Kraków","0,00","1 642,00","2 349,00","2 480,00","2 658,00"
"ISD Huta Częstochowa sp. z o.o. (w upadłości), Częsochowa","1 182,00","2,00","1,00","1,00","1,00"
"Inpost Paczkomaty sp. z o.o., Kraków","0,00","0,00","0,00","0,00","0,00"
"Krakowski Inkubator Nowych Technologii SA, Kraków","259,00","257,00","0,00","0,00","1,00"
Kraków Zielony Złocień sp. z o.o.,"0,00","0,00","0,00","0,00","0,00"
"LS Poland sp. z o.o., Łódź","67,00","57,00","57,00","18,00","17,00"
"LSC Communications sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
"Leroy Merlin Inwestycje sp. z o.o., Warszawa",NaN,NaN,NaN,NaN,NaN
Linarite Company sp. z o.o.,"0,00","0,00","0,00","0,00","0,00"
"Lisner Holding sp. z o.o., Poznań","0,00","0,00","0,00","0,00","0,00"
"MSD Polska Dystrybucja sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
"Marketing Investment Group SA, Kraków","1 700,00",NaN,NaN,NaN,NaN
"Martyna SA, Wągrowiec","11,00","20,00","0,00","2,00","0,00"
"Media Saturn Logistyka sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
"Milkpartners Polska sp. z o.o., Warszawa (w upadłości)","17,00","15,00","14,00","0,00","0,00"
"Mitsubishi Electric Europe B.V. sp. z o.o. w Polsce, Balice",NaN,"239,00","290,00","296,00","342,00"
"Müller Dairy Polska sp. z o.o., Poznań","0,00","0,00","0,00","0,00","0,00"
"Novatek Green Energy sp. z o.o., Kraków","108,00","118,00","137,00","128,00","130,00"
"Okręgowa Spółdzielnia Mleczarska, Krasnystaw",NaN,"607,00","595,00","556,00","540,00"
"Onico SA GK, Warszawa","31,00","11,00","11,00","34,00","0,00"
"PBG SA w Restrukturyzacji GK, Wysogotowo","60,00",NaN,NaN,NaN,NaN
"PG Silesia sp. z o.o., Czechowice-Dziedzice","1 560,00","1 602,00","1 430,00","1 355,00",NaN
"Panalpina Polska sp. z o.o., Wrocław","281,00","259,00","0,00","0,00","0,00"
"Panattoni Poland sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
Payholding sp. z o.o.,"0,00","0,00","0,00","0,00","0,00"
"Pittsburgh Glass Works (Poland) sp. z o.o., Środa Śląska",NaN,NaN,NaN,NaN,"279,00"
"Pol Power sp. z o.o., Komorniki","0,00","0,00","1,00","1,00","6,80"
"Polimex Opole sp. z o.o. sp.k., Opole","75,00","0,00","0,00","0,00","0,00"
"Polskie Radio SA, Warszawa",NaN,"1 252,00","1 227,00","1 226,00","1 151,00"
"Rainbow Tours SA GK, Łódź",NaN,NaN,NaN,NaN,NaN
Rzeszowskie Zakłady Drobiarskie Res-Drob sp. z o.o.,"361,00","250,00","251,00",NaN,NaN
Samsung SDS Global SCL Poland sp. z o.o.,NaN,NaN,NaN,"110,00","100,00"
"Smyk Holding SA GK, Warszawa",NaN,NaN,NaN,"2 989,00","2 947,00"
Top Secret sp. z o.o. (w upadłości),"93,00",NaN,"90,00",NaN,"0,00"
"Vershold Polska sp. z o.o., Warszawa",NaN,"0,00","0,00","0,00","0,00"
"Vicis New Investments SA, Warszawa","476,00","476,00","0,00","0,00","0,00"
"Warsaw Gas Trading sp. z o.o., Warszawa","0,00","0,00","0,00","0,00","0,00"
"Wexler Development sp. z o.o., Katowice","5,00","5,00","4,00","2,00","0,00"
"Wirtualna Polska Media SA, Warszawa",NaN,NaN,NaN,NaN,NaN
"Woodeco Wieruszów sp. z o.o., Wieruszów",NaN,NaN,NaN,NaN,NaN
"Woodeco sp. z o.o., Wrocław",NaN,NaN,NaN,NaN,NaN

In [9]:
#CHECK OF FILTERING

# Select the columns you want to include in the groupby and describe operations
selected_columns = ['Sales', 'Employment']

# Group by Year' and apply describe to the selected columns only
df_summary = df.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
df_filter_summary = df_filter.groupby(['Year'], observed=False)[selected_columns].describe().transpose()
display(df_summary, df_filter_summary)

# Show max and min company
selected_columns = ['Name','Sales', 'Employment']
display(df_filter['Name'].nunique())
display(df_filter.loc[df_filter['Sales'].idxmax(),selected_columns])
display(df_filter.loc[df_filter[df_filter['Year'] == 2023]['Sales'].idxmin(),selected_columns])

display(df_filter[selected_columns].head())

display(df_filter[selected_columns].tail())

Year                       2019          2020           2021           2022  \
Sales      count       1 875,00      1 875,00       1 875,00       1 876,00
           mean    1 285 566,66  1 269 689,80   1 531 051,95   1 997 108,08
           std     3 641 718,65  3 390 298,48   4 427 246,14   7 768 226,40
           min             0,00          0,00           0,00           0,00
           25%       376 727,61    366 596,79     432 253,51     508 462,24
           50%       550 627,00    542 112,00     662 717,00     812 381,00
           75%     1 013 811,03  1 013 751,00   1 183 304,13   1 447 064,48
           max   111 203 000,00 86 180 000,00 131 341 000,00 282 415 000,00
Employment count       1 855,00      1 850,00       1 854,00       1 859,00
           mean        1 584,16      1 423,33       1 450,03       1 466,95
           std         7 155,08      4 072,58       4 100,38       4 263,77
           min             0,00          0,00           0,00           0,00
           25%           223,00        220,00         225,00         227,00
           50%           510,00        505,50         512,00         518,00
           75%         1 189,50      1 168,50       1 182,50       1 198,50
           max       238 033,00     78 873,00      74 350,50      77 726,70

Year                       2023
Sales      count       1 876,00
           mean    2 105 297,90
           std     9 919 654,05
           min       -10 011,19
           25%       502 599,02
           50%       796 060,85
           75%     1 494 922,03
           max   371 916 000,00
Employment count       1 861,00
           mean        1 508,49
           std         4 603,60
           min             0,00
           25%           224,00
           50%           516,00
           75%         1 184,00
           max        79 292,00

Year                       2019          2020           2021           2022  \
Sales      count       1 814,00      1 814,00       1 813,00       1 814,00
           mean    1 301 680,60  1 289 160,69   1 559 954,70   2 033 126,62
           std     3 695 487,48  3 438 666,44   4 495 084,71   7 892 114,22
           min         4 743,00      1 745,00          28,00          28,00
           25%       377 983,25    373 401,90     436 862,25     520 017,01
           50%       556 471,57    549 817,53     672 871,97     825 161,66
           75%     1 020 723,00  1 015 698,17   1 195 422,00   1 454 891,00
           max   111 203 000,00 86 180 000,00 131 341 000,00 282 415 000,00
Employment count       1 814,00      1 809,00       1 809,00       1 812,00
           mean        1 611,56      1 447,17       1 471,18       1 487,21
           std         7 230,97      4 111,71       4 140,96       4 308,18
           min             1,00          1,00           1,00           1,00
           25%           232,00        227,00         232,00         238,00
           50%           522,50        513,00         525,00         531,00
           75%         1 209,75      1 178,00       1 192,00       1 206,50
           max       238 033,00     78 873,00      74 350,50      77 726,70

Year                       2023
Sales      count       1 814,00
           mean    2 145 378,05
           std    10 080 479,47
           min            21,00
           25%       512 818,84
           50%       809 442,68
           75%     1 500 352,19
           max   371 916 000,00
Employment count       1 814,00
           mean        1 534,54
           std         4 653,35
           min             1,00
           25%           240,25
           50%           530,50
           75%         1 202,50
           max        79 292,00

1814

Name          Orlen SA GK, Płock
Sales             371 916 000,00
Employment             66 554,00
Name: 4, dtype: object

Name          Zakłady Mięsne Henryk Kania SA w upadłości
Sales                                              21,00
Employment                                          4,00
Name: 6835, dtype: object

                 Name          Sales  Employment
0  Orlen SA GK, Płock  86 180 000,00   33 377,00
1  Orlen SA GK, Płock 111 203 000,00   22 337,00
2  Orlen SA GK, Płock 131 341 000,00   35 424,00
3  Orlen SA GK, Płock 282 415 000,00   64 494,00
4  Orlen SA GK, Płock 371 916 000,00   66 554,00

                                     Name      Sales  Employment
9375  Intermeble sp. z o.o. sp.k., Poznań  65 528,83      484,00
9376  Intermeble sp. z o.o. sp.k., Poznań 286 980,00      516,00
9377  Intermeble sp. z o.o. sp.k., Poznań 290 192,76         NaN
9378  Intermeble sp. z o.o. sp.k., Poznań 378 127,93      480,00
9379  Intermeble sp. z o.o. sp.k., Poznań 414 612,29      473,00

In [10]:
#ADDING DESCRIPTIVE ANALYSIS DIMENSIONS

# Create a copy of df_filter to avoid the SettingWithCopyWarning
df_filter = df_filter.copy()

#Export as % of Sales
df_filter['Export as % of Sales']= df_filter['Export Sales'] / df_filter['Sales'] *100

#ROA / ROS / ROE
df_filter['ROS']= df_filter['Net Profit'] / df_filter['Sales']
df_filter['ROA']= df_filter['Net Profit'] / df_filter['BS']  
df_filter['ROE']= df_filter['Net Profit'] / df_filter['Equity']

# Polish / Foreign Companies
df_filter['P/F'] = np.where((df_filter['Owner Type'].astype(str).str[:1] == '5'), 'F', 'P')
df_filter['P/F'] = df_filter['P/F'].astype('category')

# BalanceSheet Strength - Equity / BS
df_filter['BS'] = df_filter['BS'].replace(0, np.nan) # Replace 0 in the BS column with NaN to avoid division by zero
df_filter['BS_Strength'] = df_filter['Equity'] / df_filter['BS']

# Human Capital Proxy - Staff costs / employment
df_filter['Human_Capital'] = df_filter['Staff costs'] / df_filter['Employment']

# GVA (Gross Profit + Staff Costs)
df_filter['GVA']=df_filter['Gross Profit'] + df_filter['Staff costs']

# Productivity
df_filter['Productivity']=df_filter['GVA'] / df_filter['Employment']

In [11]:
#SALES & PROFITABILITY STATISTICS

# Isolate the annual growth rate threshold
inflation = 8.5 # (38,5% inflation between 2019 and 2023 - 3,4%	5,1%	14,4%	11,4%)
stability_threshold = 10 #(97,2% of nominal compound growth between 2019 and 2023)
growth_threshold = 20 #(172,8% of nominal compound growth between 2019 and 2023)

# Pivot the DataFrame to make year-based comparison easier for both Sales and Export
#(use only with 2023 set as a filter)
pivot_sales = df_filter.pivot(index='Name', columns='Year', values='Sales')
pivot_export_sales = df_filter.pivot(index='Name', columns='Year', values='Export Sales')
pivot_gva = df_filter.pivot(index='Name', columns='Year', values='GVA')

# High Internationalisation Export Sales > 25% of Sales
pivot_sales['Hint25'] = (pivot_export_sales[2023] / pivot_sales[2023]) > 0.25
pivot_sales['Hint25'] = pivot_sales['Hint25'].apply(lambda x: 'Exp>25' if x else 'Exp<25')

# High Internationalisation Export Sales > 50% of Sales
pivot_sales['Hint50'] = (pivot_export_sales[2023] / pivot_sales[2023]) > 0.50
pivot_sales['Hint50'] = pivot_sales['Hint50'].apply(lambda x: 'Exp>50' if x else 'Exp<50')

# HGX Export Driven
pivot_sales['HGX'] = (pivot_export_sales[2023] / pivot_sales[2023]) > (pivot_export_sales[2019] / pivot_sales[2019])
pivot_sales['HGX'] = pivot_sales['HGX'].apply(lambda x: 'Increased Export Intensity' if x else 'Decreased Export Intensity')

# HGX Export Driven
pivot_sales['HGX%'] = pivot_export_sales[2023] / pivot_sales[2023] - pivot_export_sales[2019] / pivot_sales[2019]


# Sales Growth_2023_2019 (Total and Annualised Growth)
pivot_sales['SGrowth_2023_2019'] = (pivot_sales[2023] - pivot_sales[2019]) / pivot_sales[2019] * 100
pivot_sales['Annualised_Growth'] = ((pivot_sales[2023] / pivot_sales[2019]) ** (1/4) - 1) * 100
# Sales Growth 2023_2019 - ln transformation
pivot_sales['LSGrowth_2023_2019'] = np.log(pivot_sales[2023]) - np.log(pivot_sales[2019])

pivot_sales['RealSales_2023'] = pivot_sales[2023] / 1.38
pivot_sales['RSGrowth_2023_2019'] = ((pivot_sales[2023] / 1.38) - pivot_sales[2019]) / pivot_sales[2019] * 100
pivot_sales['LRSGrowth_2023_2019'] = np.log(pivot_sales['RealSales_2023']) - np.log(pivot_sales[2019])

# Sales Drop Conditions

pivot_sales['Drop_Sales_2020'] = (pivot_sales[2020]/(1+0.034) < pivot_sales[2019])
pivot_sales['Drop_Sales_2020'] = pivot_sales['Drop_Sales_2020'].apply(lambda x: 'Yes' if x else 'No')

pivot_sales['Drop_Sales_2023'] = (pivot_sales[2023]/(1+0.114) < pivot_sales[2022])
pivot_sales['Drop_Sales_2023'] = pivot_sales['Drop_Sales_2023'].apply(lambda x: 'Yes' if x else 'No')

pivot_sales['Drop_Sales_Both'] = (pivot_sales[2023]/(1+0.114) < pivot_sales[2022]) & (pivot_sales[2020]/(1+0.034) < pivot_sales[2019])
pivot_sales['Drop_Sales_Both'] = pivot_sales['Drop_Sales_Both'].apply(lambda x: 'Yes' if x else 'No')


# GVA Growth_2023_2019 (in PLN)
pivot_gva['GVAGrowth_2023_2019'] = (pivot_gva[2023] - pivot_gva[2019])


# Add Growth column with 3 growth categories
def categorize_growth(row):
    if row['Annualised_Growth'] > (growth_threshold + inflation):
        return '3.Very High'
    elif (stability_threshold + inflation) < row['Annualised_Growth'] <= (growth_threshold + inflation):
        return '2.High'
    elif inflation < row['Annualised_Growth'] <= (stability_threshold + inflation):
        return '1.Moderate'
    else:
        return '0.Below Inflation'

pivot_sales['SGrowth_3'] = pivot_sales.apply(categorize_growth, axis=1)

# Add # Add Growth column with 2 growth categories
def categorize_growth1(row):
    if row['Annualised_Growth'] > (growth_threshold):
        return '3.High Growth'
    elif inflation <= row['Annualised_Growth'] <= (growth_threshold):
        return '2.Stable'
    elif 0 < row['Annualised_Growth'] <= inflation:
        return '1.Declining'
    else:
        return '0.Stressed'             

pivot_sales['SGrowth_2'] = pivot_sales.apply(categorize_growth1, axis=1)

# Add # Add Growth column with 1 growth category
def categorize_growth2(row):
    if row['Annualised_Growth'] > (inflation):
        return 'Growing'
    else:
        return 'Declining'
pivot_sales['SGrowth_1'] = pivot_sales.apply(categorize_growth2, axis=1)

# Merge the calculated columns back to the original df_filter DataFrame
df_filter = df_filter.merge(pivot_sales[['Hint25','Hint50','HGX','HGX%','SGrowth_2023_2019','LSGrowth_2023_2019','RSGrowth_2023_2019','LRSGrowth_2023_2019','Annualised_Growth', 'Drop_Sales_2020', 'Drop_Sales_2023','Drop_Sales_Both','SGrowth_3','SGrowth_2','SGrowth_1']], on='Name')
df_filter = df_filter.merge(pivot_gva['GVAGrowth_2023_2019'], on='Name')

In [12]:
#EMPLOYMENT STATISTICS

# Pivot the DataFrame to make year-based comparison easier for Employment
#(use only with 2023 set as a filter)
pivot_employment = df_filter.pivot(index='Name', columns='Year', values='Employment')
pivot_productivity = df_filter.pivot(index='Name',columns='Year',values='Productivity')

# Calculate Employment Growth_2023_2019 (Total Growth)
pivot_employment['EGrowth_2023_2019'] = (pivot_employment[2023] - pivot_employment[2019]) / pivot_employment[2019] * 100
# Employment Growth (Percentage) - ln transformation
pivot_employment['LEGrowth_2023_2019'] = np.log(pivot_employment[2023]) - np.log(pivot_employment[2019])

pivot_employment['Annualised_EGrowth'] = ((pivot_employment[2023] / pivot_employment[2019]) ** (1/4) - 1) * 100

# Calculate Productivity Growth_2023_2019 (Total Growth)
pivot_productivity['PGrowth_2023_2019'] = pivot_productivity[2023] - pivot_productivity[2019]


# Add Growth column with 3 categories
def categorize_egrowth(row):
    if row['EGrowth_2023_2019'] < 0:
        return '0.Reducing'
    elif (0) < row['Annualised_EGrowth'] <= (1.10):
        return '1.Sustaining'
    else:
        return '2.Hiring'

pivot_employment['EGrowth_3'] = pivot_employment.apply(categorize_egrowth, axis=1)

# Add Growth column with 2 categories
def categorize_egrowth1(row):
    if row['EGrowth_2023_2019'] < 0:
        return 'Reducing'
    else:
        return 'Hiring'

pivot_employment['EGrowth_2'] = pivot_employment.apply(categorize_egrowth1, axis=1)
    
# Calculate Employment Drop conditions
#pivot_employment['Drop_Employment'] = (pivot_employment[2020] < pivot_employment[2019]) | (pivot_employment[2021] < pivot_employment[2020]) | (pivot_employment[2022] < pivot_employment[2021]) | (pivot_employment[2023] < pivot_employment[2022])
pivot_employment['Drop_Employment'] = (pivot_employment[2020] < pivot_employment[2019])
pivot_employment['Drop_Employment'] = pivot_employment['Drop_Employment'].apply(lambda x: 'Yes' if x else 'No')

# Step 5: Merge the calculated columns back to the original df_filter DataFrame
df_filter = df_filter.merge(pivot_employment[['EGrowth_2023_2019','LEGrowth_2023_2019','Annualised_EGrowth','Drop_Employment','EGrowth_3','EGrowth_2']], on='Name')
df_filter = df_filter.merge(pivot_productivity['PGrowth_2023_2019'], on='Name')

In [13]:
#ADDING ADDITIONAL REGRESSION ANALYSIS DIMENSIONS

#np.arcsinh() used for all variables because it handles negative 
#zero, and positive values consistently, compresses outliers effectively,
#and ensures robustness across your regression analysis.
#arcsinh(x)=ln(x+ squared root(x^2+1))


# Starting Profit - ROS in 2019
ros_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['ROS'] # Step 1: Extract 2019 ROS values
df_filter['Starting_Profit'] = df_filter['Name'].map(ros_2019)# Step 2: Map 2019 ROS values to the 'Starting_Profit' column for all rows

# Starting Internationalisation level - #Export as % of Sales in 2019
Starting_INT = df_filter[df_filter['Year'] == 2019].set_index('Name')['Export as % of Sales'] # Step 1: Extract 2019 Export as % of Sales values
df_filter['Starting_INT'] = df_filter['Name'].map(Starting_INT)# Step 2: Map 2019 Export as % values to the 'Starting_INT' column for all rows

#Starting BS Strength
bs_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['BS_Strength'] # Step 1: Extract 2019 BS_Strength values
df_filter['Starting_BS_Strength'] = df_filter['Name'].map(bs_2019)# Step 2: Map 2019 ROS values to the 'Starting_Profit' column for all rows

# Starting Size - natural log of Sales for 2019
ln_sales_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Sales'].apply(np.log)
df_filter['Starting_Size_ln'] = df_filter['Name'].map(ln_sales_2019)  # Step 2: Map these values to the 'Starting_Size' column

#Starting HC Strength
hc_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Human_Capital']
df_filter['Starting_Human_Capital']=df_filter['Name'].map(hc_2019)

# Starting GVA - GVA in 2019
gva_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['GVA'] # Step 1: Extract 2019 GVA values
df_filter['Starting_GVA'] = df_filter['Name'].map(gva_2019)# Step 2: Map 2019 GVA values to the 'Starting_GVA' column for all rows

# Starting Productivity - Productivity in 2019
productivity_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Productivity'] # Step 1: Extract 2019 Productivity values
df_filter['Starting_Prod'] = df_filter['Name'].map(productivity_2019)# Step 2: Map 2019 Productivity values to the 'Starting_Prod' column for all rows


#OPTIONAL arcsinh calculations

# Starting Size - arcsinh sales in 2019
#arcsinh_sales_2019 = df_filter[df_filter['Year'] == 2019].set_index('Name')['Sales'].apply(np.arcsinh)  # Step 1: Calculate arcsinh(Sales) for 2019
#f_filter['Starting_Size_arc'] = df_filter['Name'].map(arcsinh_sales_2019)  # Step 2: Map these values to the 'Starting_Size' column


# Sales Growth (Percentage) - arcsinh transformation
#df_filter['ASGrowth_2023_2019'] = np.arcsinh(df_filter['SGrowth_2023_2019'] / 100)

# Real Sales Growth (Percentage) - arcsinh transformation
#df_filter['ARSGrowth_2023_2019'] = np.arcsinh(df_filter['RSGrowth_2023_2019'] / 100)

# Employment Growth (Percentage) - arcsinh transformation
#df_filter['AEGrowth_2023_2019'] = np.arcsinh(df_filter['EGrowth_2023_2019'] / 100)

# GVA Growth (Nominal PLN) - arcsinh transformation
#df_filter['AGVAGrowth_2023_2019'] = np.arcsinh(df_filter['GVAGrowth_2023_2019'])

# Productivity Growth (Nominal PLN) - arcsinh transformation
#df_filter['APGrowth_2023_2019'] = np.arcsinh(df_filter['PGrowth_2023_2019'])

In [14]:
# Filter for year 2023 and get top 10 by sales growth
top_10_growth_2023 = df_filter[df_filter['Year'] == 2023][['Name', 'SGrowth_2023_2019']]\
    .sort_values(by='SGrowth_2023_2019', ascending=False).head(10)

# Correct: Sort ascending to get bottom 10
bottom_10_growth_2023 = df_filter[df_filter['Year'] == 2023][['Name', 'SGrowth_2023_2019']]\
    .sort_values(by='SGrowth_2023_2019', ascending=True).head(10)

display(top_10_growth_2023)

display(bottom_10_growth_2023)


# DATA WITH COMMENTS
df_filter.to_excel('2000 Analysis Python CALCULATED.xlsx', index=False)

print("DataFrame 'df_filter' has been saved to '2000 Analysis Python CALCULATED.xlsx'.")

                                                 Name  SGrowth_2023_2019
2004              Ignitis Polska sp. z o.o., Warszawa          35 355,01
7369                 Axpo Polska sp. z o.o., Warszawa           2 732,35
1269    Grupa Kapitałowa Specjał sp. z o.o., Warszawa           1 167,12
1589                        Eniq sp. z o.o., Katowice             645,85
3273               Bunge Polska sp. z o.o., Kruszwica             625,95
5119         ZF CV Systems Poland sp. z o.o., Wrocław             550,82
8799  Viessmann Technika Grzewcza sp. z o.o., Legnica             500,15
7994                      Enefit sp. z o.o., Warszawa             447,03
124      Totalizator Sportowy sp. z o.o. GK, Warszawa             428,35
6078             Arcturus Bunker sp. z o.o., Szczecin             421,82

                                                   Name  SGrowth_2023_2019
6645         Zakłady Mięsne Henryk Kania SA w upadłości             -99,99
7625  Thyssenkrupp Materials Processing Europe sp. z...             -99,89
2895            Gas Storage Poland sp. z o.o., Kosakowo             -99,88
4285                      KTK Polska sp. z o.o., Gdańsk             -99,62
1282                           PT Dystrybucja SA, Radom             -99,21
2311              Interfood Polska sp. z o.o., Warszawa             -98,52
6095  Elektrobudowa SA w upadłości likwidacyjnej GK,...             -98,35
5145                   Eiffage Polska Serwis sp. z o.o.             -96,14
3445                  SUEK Polska sp. z o.o., Białystok             -96,05
3460               Purefert Polska sp. z o.o., Warszawa             -95,50

DataFrame 'df_filter' has been saved to '2000 Analysis Python CALCULATED.xlsx'.

In [15]:
# SET THE ANALYTICAL FILTERS

count_df_filter = df_filter[df_filter['Year'] == 2023].shape[0]
print("Number of companies before filtering = ", count_df_filter)

# Identify names manually highlighted for removal
manually_remove = df_filter[
    (df_filter['Year'].isin([2019, 2023])) & 
    (df_filter['Remove'] == 1)
]['Name'].unique()

# Identify names with outlier Export as % of Sales
export_error = df_filter[
    (df_filter['Year'].isin([2019, 2023])) & 
    (df_filter['Export as % of Sales'] > 100.001)
]['Name'].unique()

# Remove those companies + those not present in 2019 list
df_filter = df_filter[
    df_filter['2019'].notna() & (~df_filter['Name'].isin(export_error)) &
    (~df_filter['Name'].isin(manually_remove))
]


# Optional filter: remove specific sectors
# Uncomment next line to activate
# company_filter = df_filter[df_filter['PKD'] == '3514']

if 'company_filter' in locals():
    df_filter = df_filter[~df_filter.index.isin(company_filter.index)]
    num_sector_removed = company_filter['Name'].nunique()
else:
    num_sector_removed = 0

# Show results
print(f"Number of companies removed due to manual removals: {len(manually_remove)}")
print(f"Number of companies removed due to Export as % of Sales > 100 in 2019 or 2023: {len(export_error)}")
# print(f"Number of companies removed due to sector: {company_filter['Name'].nunique()}")

count_df_filter = df_filter[df_filter['Year'] == 2023].shape[0]
print("Number of companies after filtering = ", count_df_filter)

print (manually_remove)
print (export_error)

Number of companies before filtering =  1814
Number of companies removed due to manual removals: 6
Number of companies removed due to Export as % of Sales > 100 in 2019 or 2023: 0
Number of companies after filtering =  1808
['Orlen SA GK, Płock' 'Ignitis Polska sp. z o.o., Warszawa'
 'NSK Steering Systems Europe sp. z o.o., Wałbrzych'
 'Toyota Boshoku Poland sp. z o.o., Wykroty'
 'Elektrobudowa SA w upadłości likwidacyjnej GK, Katowice'
 'Zakłady Mięsne Henryk Kania SA w upadłości']
[]

In [16]:
# CLOSING CODES
df_filter.to_excel('2000 Analysis Python CHANGED.xlsx', index=False)

print("DataFrame 'df_filter' has been saved to '2000 Analysis Python CHANGED.xlsx'.")

DataFrame 'df_filter' has been saved to '2000 Analysis Python CHANGED.xlsx'.

In [17]:
df_summary = df_filter.groupby(['Year'], observed=False)[['Sales','Employment']].describe().transpose()

display(df_summary)

df_summary.to_excel('Results/Summary Stats.xlsx', index=True)

Year                      2019          2020          2021          2022  \
Sales      count      1 808,00      1 808,00      1 807,00      1 808,00
           mean   1 243 251,51  1 245 000,74  1 491 683,09  1 882 458,56
           std    2 648 050,22  2 805 468,70  3 307 155,68  4 353 947,58
           min      193 371,00     76 744,00      7 380,00     12 233,00
           25%      378 055,75    373 986,06    437 303,85    520 518,84
           50%      556 471,57    550 340,50    673 220,00    826 146,00
           75%    1 021 337,50  1 015 713,25  1 195 942,50  1 456 051,00
           max   55 573 747,04 61 216 804,38 68 246 695,47 85 034 775,00
Employment count      1 808,00      1 803,00      1 803,00      1 806,00
           mean       1 602,35      1 432,31      1 455,59      1 455,72
           std        7 226,35      4 048,85      4 069,47      4 051,83
           min            1,00          1,00          1,00          1,00
           25%          232,00        227,50        234,00        238,00
           50%          519,50        513,00        525,00        531,50
           75%        1 209,25      1 179,00      1 192,50      1 211,50
           max      238 033,00     78 873,00     74 350,50     77 726,70

Year                      2023
Sales      count      1 808,00
           mean   1 944 908,83
           std    5 122 420,47
           min          393,74
           25%      512 852,66
           50%      809 442,68
           75%    1 500 084,58
           max   98 022 928,00
Employment count      1 808,00
           mean       1 502,09
           std        4 402,30
           min            1,00
           25%          241,00
           50%          531,00
           75%        1 203,00
           max       79 292,00

In [18]:
# Filter for 2023
df_2023 = df_filter[df_filter['Year'] == 2023]

# Choose variables to summarize
columns_of_interest = ['LSGrowth_2023_2019','Starting_INT', 'Starting_BS_Strength','Starting_Size_ln', 'Starting_Profit',
                      'HGX%']  # add more if needed

# Compute and transpose the summary
df_summary_2023 = df_2023[columns_of_interest].describe().transpose()

# Display and export
display(df_summary_2023.T)
df_summary_2023.T.to_excel('Results/Summary Stats 2023.xlsx')

,LSGrowth_2023_2019,Starting_INT,Starting_BS_Strength,Starting_Size_ln,Starting_Profit,HGX%
count,"1 808,00","1 800,00","1 801,00","1 808,00","1 803,00","1 788,00"
mean,"0,29","31,17","0,42","13,47","0,04","-0,01"
std,"0,54","35,14","0,25","0,85","0,08","0,16"
min,"-6,77","0,00","-1,44","12,17","-0,70","-1,00"
25%,"0,14","0,15","0,25","12,84","0,01","-0,02"
50%,"0,32","14,17","0,41","13,23","0,03","0,00"
75%,"0,50","61,32","0,59","13,84","0,06","0,02"
max,"3,34","100,00","0,98","17,83","0,90","1,00"